(function(){
  'use strict';
  var BASE='https://losownik.pl';
  var SUPPORTED=['pl','en','de','es','fr','it','pt','ru','cs','uk'];
  var NAMES={pl:'Polski',en:'English',de:'Deutsch',es:'Español',fr:'Français',it:'Italiano',pt:'Português',ru:'Русский',cs:'Čeština',uk:'Українська'};
  var NAV={pl:{Start:'Start',Kostka:'Kostka',Mecz:'Mecz','Imię':'Imię',Lotto:'Lotto','Koło':'Koło',Ruletka:'Ruletka',Moneta:'Moneta',Kolor:'Kolor,Karty':'Karty'},en:{Start:'Home',Kostka:'Dice',Mecz:'Match',Imię:'Name',Lotto:'Lotto','Koło':'Wheel',Ruletka:'Roulette',Moneta:'Coin',Kolor:'Color',Karty:'Cards',Drużyny:'Teams',Kolejność:'Order',RPG:'RPG','Wylicz.':'Picker',Liczba:'Number'},de:{Start:'Start',Kostka:'Würfel',Mecz:'Spiel',Imię:'Name',Lotto:'Lotto','Koło':'Rad',Ruletka:'Roulette',Moneta:'Münze',Kolor:'Farbe',Karty:'Karten',Drużyny:'Teams',Kolejność:'Reihenf.',RPG:'RPG','Wylicz.':'Auswahl',Liczba:'Zahl'},es:{Start:'Inicio',Kostka:'Dado',Mecz:'Partido',Imię:'Nombre',Lotto:'Loto','Koło':'Ruleta',Ruletka:'Ruleta',Moneta:'Moneda',Kolor:'Color',Karty:'Cartas',Drużyny:'Equipos',Kolejność:'Orden',RPG:'RPG','Wylicz.':'Elegir',Liczba:'Número'},fr:{Start:'Accueil',Kostka:'Dé',Mecz:'Match',Imię:'Prénom',Lotto:'Loto','Koło':'Roue',Ruletka:'Roulette',Moneta:'Pièce',Kolor:'Couleur',Karty:'Cartes',Drużyny:'Équipes',Kolejność:'Ordre',RPG:'RPG','Wylicz.':'Tirage',Liczba:'Nombre'},it:{Start:'Home',Kostka:'Dado',Mecz:'Partita',Imię:'Nome',Lotto:'Lotto','Koło':'Ruota',Ruletka:'Roulette',Moneta:'Moneta',Kolor:'Colore',Karty:'Carte',Drużyny:'Squadre',Kolejność:'Ordine',RPG:'RPG','Wylicz.':'Scelta',Liczba:'Numero'},pt:{Start:'Início',Kostka:'Dado',Mecz:'Jogo',Imię:'Nome',Lotto:'Loto','Koło':'Roleta',Ruletka:'Roleta',Moneta:'Moeda',Kolor:'Cor',Karty:'Cartas',Drużyny:'Equipes',Kolejność:'Ordem',RPG:'RPG','Wylicz.':'Sortear',Liczba:'Número'},ru:{Start:'Главная',Kostka:'Кубик',Mecz:'Матч',Imię:'Имя',Lotto:'Лото','Koło':'Колесо',Ruletka:'Рулетка',Moneta:'Монета',Kolor:'Цвет',Karty:'Карты',Drużyny:'Команды',Kolejność:'Порядок',RPG:'RPG','Wylicz.':'Выбор',Liczba:'Число'},cs:{Start:'Domů',Kostka:'Kostka',Mecz:'Zápas',Imię:'Jméno',Lotto:'Loto','Koło':'Kolo',Ruletka:'Ruleta',Moneta:'Mince',Kolor:'Barva',Karty:'Karty',Drużyny:'Týmy',Kolejność:'Pořadí',RPG:'RPG','Wylicz.':'Výběr',Liczba:'Číslo'},uk:{Start:'Головна',Kostka:'Кубик',Mecz:'Матч',Imię:'Імʼя',Lotto:'Лото','Koło':'Колесо',Ruletka:'Рулетка',Moneta:'Монета',Kolor:'Колір',Karty:'Карти',Drużyny:'Команди',Kolejność:'Порядок',RPG:'RPG','Wylicz.':'Вибір',Liczba:'Число'}};
  var PAGE={
    '/':{pl:['Losownik.pl – internetowa maszyna losująca','Losownik.pl – internetowa maszyna losująca. Rzuć kostką, wylosuj imię, wytypuj wynik meczu, kręć kołem fortuny i więcej!'],en:['Random generator online | Losownik.pl','Free online random tools: dice roller, random name generator, match score picker, lottery numbers, wheel spinner, coin flip and more.'],de:['Zufallsgenerator online | Losownik.pl','Kostenlose Zufalls-Tools: Würfel, Namensgenerator, Spielergebnis, Lottozahlen, Glücksrad, Münzwurf und mehr.'],es:['Generador aleatorio online | Losownik.pl','Herramientas aleatorias gratis: dados, nombres, resultados, números de lotería, ruleta, moneda y más.'],fr:['Générateur aléatoire en ligne | Losownik.pl','Outils aléatoires gratuits : dés, prénoms, scores, numéros de loto, roue, pile ou face et plus.'],it:['Generatore casuale online | Losownik.pl','Strumenti casuali gratis: dadi, nomi, risultati, numeri lotto, ruota, moneta e altro.'],pt:['Gerador aleatório online | Losownik.pl','Ferramentas aleatórias grátis: dados, nomes, resultados, números de loteria, roleta, moeda e mais.'],ru:['Онлайн генератор случайных результатов | Losownik.pl','Бесплатные случайные инструменты: кубики, имена, счет матча, лотерейные числа, колесо, монета и другое.'],cs:['Náhodný generátor online | Losownik.pl','Bezplatné náhodné nástroje: kostky, jména, skóre, loto čísla, kolo, mince a další.'],uk:['Онлайн генератор випадкових результатів | Losownik.pl','Безкоштовні випадкові інструменти: кубики, імена, рахунок матчу, лотерейні числа, колесо, монета та інше.']},
    '/kostka':['Dice roller online','Roll k4, k6, k8, k10, k12, k20 and k100 dice online with animation. Perfect for RPG, board games and quick random results.'],
    '/mecz':['Random match score generator','Generate a random realistic match score for football, volleyball, basketball or handball.'],
    '/imie':['Random name generator','Generate a random first name, female name, male name or full identity.'],
    '/lotto':['Lottery number generator','Generate lucky numbers for Lotto, Mini Lotto, Multi Multi and Joker.'],
    '/ruletka':['European roulette online','Spin European roulette online and check a random number, color or range.'],
    '/wyliczanka':['Random person picker','Enter names and let the random picker choose one person for you.'],
    '/liczba':['Random number generator','Generate one or many random numbers from any range.'],
    '/kolo-fortuny':['Spin the wheel online','Enter options, spin the wheel and let the random picker decide.'],
    '/moneta':['Flip a coin online','Heads or tails? Flip a coin online with a quick animation.'],
    '/kolor':['Random color generator','Generate a random color in HEX or RGB and copy it for your project.'],
    '/druzyny':['Random team generator','Divide players into equal random teams for games, sports and classroom activities.'],
    '/kolejnosc':['Random order generator','Shuffle a list and create a random order for turns, tasks or players.'],
    '/postac':['RPG character generator','Generate a random RPG character with stats, race, class and name.'],
    '/karty':['Random card draw','Draw a random card from a 52-card deck online.']
  };
  var KEY='losownik_lang';
  function path(){var p=location.pathname.replace(/\.html$/,'').replace(/\/$/,'')||'/';return p==='/index'?'/':p;}
  function currentLang(){var q=new URLSearchParams(location.search).get('lang');if(q&&SUPPORTED.indexOf(q)>=0){localStorage.setItem(KEY,q);return q;}return localStorage.getItem(KEY)||document.documentElement.lang||'pl';}
  function urlFor(p,l){return BASE+p+(l==='pl'?'':'?lang='+encodeURIComponent(l));}
  function setMeta(name,value,prop){var s=prop?'meta[property="'+name+'"]':'meta[name="'+name+'"]',m=document.querySelector(s);if(!m){m=document.createElement('meta');m.setAttribute(prop?'property':'name',name);document.head.appendChild(m);}m.setAttribute('content',value);}
  function setLink(rel,href,hreflang){var s='link[rel="'+rel+'"]'+(hreflang?'[hreflang="'+hreflang+'"]':'');var l=document.querySelector(s);if(!l){l=document.createElement('link');l.rel=rel;if(hreflang)l.hreflang=hreflang;document.head.appendChild(l);}l.href=href;}
  function pageSeo(p,l){if(PAGE[p]&&PAGE[p][l])return PAGE[p][l];var base=PAGE[p]||PAGE['/'][l]||PAGE['/'].en;if(l==='pl')return [document.title,(document.querySelector('meta[name="description"]')||{}).content||base[1]];return [base[0]+' | Losownik.pl',base[1]];}
  function applyText(l){if(l==='pl')return;var p=path(),data=window.LOSOWNIK_T&&window.LOSOWNIK_T[p]&&window.LOSOWNIK_T[p][l];if(data){var h=document.querySelector('.page-title,.hero h2');if(h&&(data.h1||data.hero))h.innerHTML=data.h1||data.hero;var d=document.querySelector('.page-desc,.hero p');if(d&&(data.desc||data.heroDesc))d.textContent=data.desc||data.heroDesc;if(data.btn)document.querySelectorAll('.generate-btn,.roll-btn,.flip-btn,.spin-btn').forEach(function(b){b.textContent=data.btn;});if(data.cards){var keys=['kostka','mecz','imie','lotto','wyliczanka','liczba','kolo','kolor','druzyny','kolejnosc','postac','moneta','karty','ruletka'];document.querySelectorAll('.tool-card').forEach(function(c,i){var k=keys[i];if(data.cards[k]){var h3=c.querySelector('h3');if(h3)h3.textContent=data.cards[k];var pp=c.querySelector('p');if(pp&&data.cards[k+'Sub'])pp.textContent=data.cards[k+'Sub'];}});}}
    var n=NAV[l]||{};document.querySelectorAll('a,.nav-label').forEach(function(el){var t=(el.textContent||'').trim();if(n[t]){if(el.children.length&&el.querySelector('.nav-icon')){Array.prototype.forEach.call(el.childNodes,function(node){if(node.nodeType===3&&node.textContent.trim())node.textContent=n[t];});}else el.textContent=n[t];}});
  }
  function switcher(l){document.querySelectorAll('.lang-switcher').forEach(function(e){e.remove();});var header=document.querySelector('header');if(!header)return;var w=document.createElement('div');w.className='lang-switcher';var s=document.createElement('select');s.className='lang-select';s.setAttribute('aria-label','Language');SUPPORTED.forEach(function(code){var o=document.createElement('option');o.value=code;o.textContent=NAMES[code];o.selected=code===l;s.appendChild(o);});s.onchange=function(){var next=s.value;localStorage.setItem(KEY,next);location.href=urlFor(path(),next);};w.appendChild(s);header.appendChild(w);}
  function preserveLang(l){if(l==='pl')return;document.querySelectorAll('a[href^="/"]').forEach(function(a){var href=a.getAttribute('href');if(!href||href.indexOf('/js/')===0||href.indexOf('/css/')===0)return;var u=new URL(href,BASE);u.searchParams.set('lang',l);a.setAttribute('href',u.pathname+u.search);});}
  function run(){var l=currentLang();if(SUPPORTED.indexOf(l)<0)l='pl';var p=path();document.documentElement.lang=l;var seo=pageSeo(p,l),u=urlFor(p,l);document.title=seo[0];setMeta('description',seo[1]);setMeta('og:title',seo[0],true);setMeta('og:description',seo[1],true);setMeta('og:url',u,true);setLink('canonical',u);SUPPORTED.forEach(function(code){setLink('alternate',urlFor(p,code),code);});setLink('alternate',urlFor(p,'pl'),'x-default');applyText(l);switcher(l);preserveLang(l);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
