/**
 * Losownik.pl - Complete i18n translations v4
 * Full translations for all 10 languages across all pages
 * Languages: pl, en, de, es, fr, it, pt, ru, cs, uk
 */
// COMMON TRANSLATIONS
window.LOSOWNIK_COMMON = {
pl:{subtitle:"Internetowa maszyna losująca",home:"Strona główna",privacy:"Polityka prywatności",footer:"Internetowa maszyna losująca",heads:"ORZEŁ",tails:"RESZKA",headsLabel:"Orzeł",tailsLabel:"Reszka",totalLabel:"Razem",draw:"Remis",homeWin:"Wygrana gospodarzy",awayWin:"Wygrana gości",sets:"Sety",set:"Set",hostLabel:"Gospodarz",guestLabel:"Gość",clickToGenerate:"Kliknij przycisk aby wylosować wynik",drawn:"Wylosowane",clickToFlip:"Kliknij monetę aby rzucić",history:"Historia rzutów",noHistory:"Brak rzutów – kliknij kostkę lub przycisk aby rozpocząć",rollResult:"Wynik rzutu",clickToRoll:"Kliknij aby rzucić",faq:"Najczęściej zadawane pytania",clickNumbers:"Kliknij przycisk aby wylosować liczby",settingsHint:"Minimum 2 opcje. Każda opcja w osobnej linii.",maleInfo:"Imię męskie",femaleInfo:"Imię żeńskie",fullMale:"Imię i nazwisko (mężczyzna)",fullFemale:"Imię i nazwisko (kobieta)",clickName:"Kliknij przycisk aby wylosować",minLabel:"Min:",maxLabel:"Maks:",countLabel:"Ilość:",playersLabel:"Gracze (po jednym w linii):",teamsLabel:"Liczba drużyn:",team:"Drużyna",itemsLabel:"Elementy (po jednym w linii):",copied:"Skopiowano!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Pozostało:",deckEmpty:'Talia pusta! Kliknij "Przetasuj"',shuffle:"Przetasuj",cards:"karty",pickerMin:"Wpisz co najmniej 2 imiona!",pickerResult:"Wylosowana osoba",candidates:"kandydatów"},
en:{subtitle:"Online random generator",home:"Home",privacy:"Privacy policy",footer:"Online random generator",heads:"HEADS",tails:"TAILS",headsLabel:"Heads",tailsLabel:"Tails",totalLabel:"Total",draw:"Draw",homeWin:"Home team wins",awayWin:"Away team wins",sets:"Sets",set:"Set",hostLabel:"Home",guestLabel:"Away",clickToGenerate:"Click the button to generate a score",drawn:"Generated at",clickToFlip:"Click the coin to flip",history:"Roll history",noHistory:"No rolls yet – click the dice or button to start",rollResult:"Roll result",clickToRoll:"Click to roll",faq:"Frequently asked questions",clickNumbers:"Click the button to generate numbers",settingsHint:"Minimum 2 options. Each option on a separate line.",maleInfo:"Male name",femaleInfo:"Female name",fullMale:"Full name (male)",fullFemale:"Full name (female)",clickName:"Click the button to generate",minLabel:"Min:",maxLabel:"Max:",countLabel:"Count:",playersLabel:"Players (one per line):",teamsLabel:"Number of teams:",team:"Team",itemsLabel:"Items (one per line):",copied:"Copied!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Remaining:",deckEmpty:'Deck empty! Click "Shuffle"',shuffle:"Shuffle",cards:"cards",pickerMin:"Enter at least 2 names!",pickerResult:"Picked person",candidates:"candidates"},
de:{subtitle:"Online Zufallsgenerator",home:"Startseite",privacy:"Datenschutz",footer:"Online Zufallsgenerator",heads:"KOPF",tails:"ZAHL",headsLabel:"Kopf",tailsLabel:"Zahl",totalLabel:"Gesamt",draw:"Unentschieden",homeWin:"Heimsieg",awayWin:"Auswärtssieg",sets:"Sätze",set:"Satz",hostLabel:"Heim",guestLabel:"Gast",clickToGenerate:"Klicke den Button um ein Ergebnis zu generieren",drawn:"Generiert um",clickToFlip:"Klicke die Münze zum Werfen",history:"Würfelverlauf",noHistory:"Noch keine Würfe – klicke den Würfel oder Button",rollResult:"Wurfergebnis",clickToRoll:"Klicken zum Würfeln",faq:"Häufig gestellte Fragen",clickNumbers:"Klicke den Button um Zahlen zu generieren",settingsHint:"Mindestens 2 Optionen. Jede Option in einer eigenen Zeile.",maleInfo:"Männlicher Name",femaleInfo:"Weiblicher Name",fullMale:"Vollständiger Name (männlich)",fullFemale:"Vollständiger Name (weiblich)",clickName:"Klicke den Button zum Generieren",minLabel:"Min:",maxLabel:"Max:",countLabel:"Anzahl:",playersLabel:"Spieler (einer pro Zeile):",teamsLabel:"Anzahl der Teams:",team:"Team",itemsLabel:"Elemente (eines pro Zeile):",copied:"Kopiert!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Verbleibend:",deckEmpty:'Deck leer! Klicke "Mischen"',shuffle:"Mischen",cards:"Karten",pickerMin:"Gib mindestens 2 Namen ein!",pickerResult:"Ausgewählte Person",candidates:"Kandidaten"},
es:{subtitle:"Generador aleatorio online",home:"Inicio",privacy:"Política de privacidad",footer:"Generador aleatorio online",heads:"CARA",tails:"CRUZ",headsLabel:"Cara",tailsLabel:"Cruz",totalLabel:"Total",draw:"Empate",homeWin:"Victoria local",awayWin:"Victoria visitante",sets:"Sets",set:"Set",hostLabel:"Local",guestLabel:"Visitante",clickToGenerate:"Haz clic en el botón para generar un resultado",drawn:"Generado a las",clickToFlip:"Haz clic en la moneda para lanzar",history:"Historial de tiradas",noHistory:"Sin tiradas – haz clic en el dado o botón para empezar",rollResult:"Resultado de la tirada",clickToRoll:"Clic para tirar",faq:"Preguntas frecuentes",clickNumbers:"Haz clic en el botón para generar números",settingsHint:"Mínimo 2 opciones. Cada opción en una línea separada.",maleInfo:"Nombre masculino",femaleInfo:"Nombre femenino",fullMale:"Nombre completo (hombre)",fullFemale:"Nombre completo (mujer)",clickName:"Haz clic en el botón para generar",minLabel:"Mín:",maxLabel:"Máx:",countLabel:"Cantidad:",playersLabel:"Jugadores (uno por línea):",teamsLabel:"Número de equipos:",team:"Equipo",itemsLabel:"Elementos (uno por línea):",copied:"¡Copiado!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Restantes:",deckEmpty:'¡Baraja vacía! Haz clic en "Barajar"',shuffle:"Barajar",cards:"cartas",pickerMin:"¡Introduce al menos 2 nombres!",pickerResult:"Persona elegida",candidates:"candidatos"},
fr:{subtitle:"Générateur aléatoire en ligne",home:"Accueil",privacy:"Politique de confidentialité",footer:"Générateur aléatoire en ligne",heads:"PILE",tails:"FACE",headsLabel:"Pile",tailsLabel:"Face",totalLabel:"Total",draw:"Match nul",homeWin:"Victoire domicile",awayWin:"Victoire extérieur",sets:"Sets",set:"Set",hostLabel:"Domicile",guestLabel:"Extérieur",clickToGenerate:"Cliquez sur le bouton pour générer un score",drawn:"Généré à",clickToFlip:"Cliquez sur la pièce pour lancer",history:"Historique des lancers",noHistory:"Aucun lancer – cliquez sur le dé ou le bouton",rollResult:"Résultat du lancer",clickToRoll:"Cliquez pour lancer",faq:"Questions fréquentes",clickNumbers:"Cliquez sur le bouton pour générer des numéros",settingsHint:"Minimum 2 options. Chaque option sur une ligne séparée.",maleInfo:"Prénom masculin",femaleInfo:"Prénom féminin",fullMale:"Nom complet (homme)",fullFemale:"Nom complet (femme)",clickName:"Cliquez sur le bouton pour générer",minLabel:"Min :",maxLabel:"Max :",countLabel:"Quantité :",playersLabel:"Joueurs (un par ligne) :",teamsLabel:"Nombre d'équipes :",team:"Équipe",itemsLabel:"Éléments (un par ligne) :",copied:"Copié !",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Restantes :",deckEmpty:'Jeu vide ! Cliquez sur "Mélanger"',shuffle:"Mélanger",cards:"cartes",pickerMin:"Entrez au moins 2 noms !",pickerResult:"Personne choisie",candidates:"candidats"},
it:{subtitle:"Generatore casuale online",home:"Home",privacy:"Privacy policy",footer:"Generatore casuale online",heads:"TESTA",tails:"CROCE",headsLabel:"Testa",tailsLabel:"Croce",totalLabel:"Totale",draw:"Pareggio",homeWin:"Vittoria casa",awayWin:"Vittoria ospiti",sets:"Set",set:"Set",hostLabel:"Casa",guestLabel:"Ospiti",clickToGenerate:"Clicca il pulsante per generare un risultato",drawn:"Generato alle",clickToFlip:"Clicca la moneta per lanciare",history:"Cronologia lanci",noHistory:"Nessun lancio – clicca il dado o il pulsante",rollResult:"Risultato del lancio",clickToRoll:"Clicca per lanciare",faq:"Domande frequenti",clickNumbers:"Clicca il pulsante per generare numeri",settingsHint:"Minimo 2 opzioni. Ogni opzione su una riga separata.",maleInfo:"Nome maschile",femaleInfo:"Nome femminile",fullMale:"Nome completo (uomo)",fullFemale:"Nome completo (donna)",clickName:"Clicca il pulsante per generare",minLabel:"Min:",maxLabel:"Max:",countLabel:"Quantità:",playersLabel:"Giocatori (uno per riga):",teamsLabel:"Numero di squadre:",team:"Squadra",itemsLabel:"Elementi (uno per riga):",copied:"Copiato!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Rimanenti:",deckEmpty:'Mazzo vuoto! Clicca "Mescola"',shuffle:"Mescola",cards:"carte",pickerMin:"Inserisci almeno 2 nomi!",pickerResult:"Persona scelta",candidates:"candidati"},
pt:{subtitle:"Gerador aleatório online",home:"Início",privacy:"Política de privacidade",footer:"Gerador aleatório online",heads:"CARA",tails:"COROA",headsLabel:"Cara",tailsLabel:"Coroa",totalLabel:"Total",draw:"Empate",homeWin:"Vitória mandante",awayWin:"Vitória visitante",sets:"Sets",set:"Set",hostLabel:"Mandante",guestLabel:"Visitante",clickToGenerate:"Clique no botão para gerar um resultado",drawn:"Gerado às",clickToFlip:"Clique na moeda para lançar",history:"Histórico de lançamentos",noHistory:"Sem lançamentos – clique no dado ou botão para começar",rollResult:"Resultado do lançamento",clickToRoll:"Clique para lançar",faq:"Perguntas frequentes",clickNumbers:"Clique no botão para gerar números",settingsHint:"Mínimo 2 opções. Cada opção em uma linha separada.",maleInfo:"Nome masculino",femaleInfo:"Nome feminino",fullMale:"Nome completo (homem)",fullFemale:"Nome completo (mulher)",clickName:"Clique no botão para gerar",minLabel:"Mín:",maxLabel:"Máx:",countLabel:"Quantidade:",playersLabel:"Jogadores (um por linha):",teamsLabel:"Número de equipes:",team:"Equipe",itemsLabel:"Itens (um por linha):",copied:"Copiado!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Restantes:",deckEmpty:'Baralho vazio! Clique em "Embaralhar"',shuffle:"Embaralhar",cards:"cartas",pickerMin:"Insira pelo menos 2 nomes!",pickerResult:"Pessoa escolhida",candidates:"candidatos"},
ru:{subtitle:"Онлайн генератор случайностей",home:"Главная",privacy:"Политика конфиденциальности",footer:"Онлайн генератор случайностей",heads:"ОРЁЛ",tails:"РЕШКА",headsLabel:"Орёл",tailsLabel:"Решка",totalLabel:"Всего",draw:"Ничья",homeWin:"Победа хозяев",awayWin:"Победа гостей",sets:"Сеты",set:"Сет",hostLabel:"Хозяева",guestLabel:"Гости",clickToGenerate:"Нажмите кнопку чтобы сгенерировать счёт",drawn:"Сгенерировано в",clickToFlip:"Нажмите на монету чтобы подбросить",history:"История бросков",noHistory:"Нет бросков – нажмите на кубик или кнопку",rollResult:"Результат броска",clickToRoll:"Нажмите чтобы бросить",faq:"Часто задаваемые вопросы",clickNumbers:"Нажмите кнопку чтобы сгенерировать числа",settingsHint:"Минимум 2 варианта. Каждый вариант на отдельной строке.",maleInfo:"Мужское имя",femaleInfo:"Женское имя",fullMale:"Полное имя (мужчина)",fullFemale:"Полное имя (женщина)",clickName:"Нажмите кнопку для генерации",minLabel:"Мин:",maxLabel:"Макс:",countLabel:"Кол-во:",playersLabel:"Игроки (по одному в строке):",teamsLabel:"Количество команд:",team:"Команда",itemsLabel:"Элементы (по одному в строке):",copied:"Скопировано!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Осталось:",deckEmpty:'Колода пуста! Нажмите "Перетасовать"',shuffle:"Перетасовать",cards:"карт",pickerMin:"Введите минимум 2 имени!",pickerResult:"Выбранный человек",candidates:"кандидатов"},
cs:{subtitle:"Online generátor náhody",home:"Domů",privacy:"Zásady ochrany soukromí",footer:"Online generátor náhody",heads:"PANNA",tails:"OREL",headsLabel:"Panna",tailsLabel:"Orel",totalLabel:"Celkem",draw:"Remíza",homeWin:"Výhra domácích",awayWin:"Výhra hostů",sets:"Sety",set:"Set",hostLabel:"Domácí",guestLabel:"Hosté",clickToGenerate:"Klikněte na tlačítko pro vygenerování skóre",drawn:"Vygenerováno v",clickToFlip:"Klikněte na minci pro hod",history:"Historie hodů",noHistory:"Žádné hody – klikněte na kostku nebo tlačítko",rollResult:"Výsledek hodu",clickToRoll:"Klikněte pro hod",faq:"Často kladené otázky",clickNumbers:"Klikněte na tlačítko pro vygenerování čísel",settingsHint:"Minimálně 2 možnosti. Každá možnost na samostatném řádku.",maleInfo:"Mužské jméno",femaleInfo:"Ženské jméno",fullMale:"Celé jméno (muž)",fullFemale:"Celé jméno (žena)",clickName:"Klikněte na tlačítko pro vygenerování",minLabel:"Min:",maxLabel:"Max:",countLabel:"Počet:",playersLabel:"Hráči (jeden na řádek):",teamsLabel:"Počet týmů:",team:"Tým",itemsLabel:"Položky (jedna na řádek):",copied:"Zkopírováno!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Zbývá:",deckEmpty:'Balíček prázdný! Klikněte "Zamíchat"',shuffle:"Zamíchat",cards:"karet",pickerMin:"Zadejte alespoň 2 jména!",pickerResult:"Vybraná osoba",candidates:"kandidátů"},
uk:{subtitle:"Онлайн генератор випадковостей",home:"Головна",privacy:"Політика конфіденційності",footer:"Онлайн генератор випадковостей",heads:"ОРЕЛ",tails:"РЕШКА",headsLabel:"Орел",tailsLabel:"Решка",totalLabel:"Разом",draw:"Нічия",homeWin:"Перемога господарів",awayWin:"Перемога гостей",sets:"Сети",set:"Сет",hostLabel:"Господарі",guestLabel:"Гості",clickToGenerate:"Натисніть кнопку щоб згенерувати рахунок",drawn:"Згенеровано о",clickToFlip:"Натисніть на монету щоб підкинути",history:"Історія кидків",noHistory:"Немає кидків – натисніть на кубик або кнопку",rollResult:"Результат кидка",clickToRoll:"Натисніть щоб кинути",faq:"Поширені запитання",clickNumbers:"Натисніть кнопку щоб згенерувати числа",settingsHint:"Мінімум 2 варіанти. Кожен варіант в окремому рядку.",maleInfo:"Чоловіче ім'я",femaleInfo:"Жіноче ім'я",fullMale:"Повне ім'я (чоловік)",fullFemale:"Повне ім'я (жінка)",clickName:"Натисніть кнопку для генерації",minLabel:"Мін:",maxLabel:"Макс:",countLabel:"К-сть:",playersLabel:"Гравці (по одному в рядку):",teamsLabel:"Кількість команд:",team:"Команда",itemsLabel:"Елементи (по одному в рядку):",copied:"Скопійовано!",hexLabel:"HEX",rgbLabel:"RGB",hslLabel:"HSL",cardsRemaining:"Залишилось:",deckEmpty:'Колода порожня! Натисніть "Перетасувати"',shuffle:"Перетасувати",cards:"карт",pickerMin:"Введіть мінімум 2 імені!",pickerResult:"Обрана людина",candidates:"кандидатів"}
};


// META TRANSLATIONS (title + description per page per language)
window.LOSOWNIK_META = {
"/":{
en:{title:"Losownik.pl – Online random generator",desc:"Free online random generator – dice, coins, names, numbers, lotto, teams and more. No registration required!"},
de:{title:"Losownik.pl – Online Zufallsgenerator",desc:"Kostenloser Online-Zufallsgenerator – Würfel, Münzen, Namen, Zahlen, Lotto, Teams und mehr."},
es:{title:"Losownik.pl – Generador aleatorio online",desc:"Generador aleatorio online gratuito – dados, monedas, nombres, números, loto, equipos y más."},
fr:{title:"Losownik.pl – Générateur aléatoire en ligne",desc:"Générateur aléatoire gratuit – dés, pièces, prénoms, nombres, loto, équipes et plus."},
it:{title:"Losownik.pl – Generatore casuale online",desc:"Generatore casuale online gratuito – dadi, monete, nomi, numeri, lotto, squadre e altro."},
pt:{title:"Losownik.pl – Gerador aleatório online",desc:"Gerador aleatório online gratuito – dados, moedas, nomes, números, loto, equipes e mais."},
ru:{title:"Losownik.pl – Онлайн генератор случайностей",desc:"Бесплатный онлайн генератор – кубики, монеты, имена, числа, лото, команды и многое другое."},
cs:{title:"Losownik.pl – Online generátor náhody",desc:"Bezplatný online generátor – kostky, mince, jména, čísla, loto, týmy a další."},
uk:{title:"Losownik.pl – Онлайн генератор випадковостей",desc:"Безкоштовний онлайн генератор – кубики, монети, імена, числа, лото, команди та інше."}
},

"/kostka":{
en:{title:"Roll dice online – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Roll virtual dice online – d4, d6, d8, d10, d12, d20, d100 with 3D animation. Perfect for RPG and board games."},
de:{title:"Online Würfeln – W4, W6, W8, W10, W12, W20, W100 | Losownik.pl",desc:"Virtuelle Würfel online werfen – W4, W6, W8, W10, W12, W20, W100 mit 3D-Animation."},
es:{title:"Tirar dados online – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Tira dados virtuales online – d4, d6, d8, d10, d12, d20, d100 con animación 3D."},
fr:{title:"Lancer des dés en ligne – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Lancez des dés virtuels en ligne – d4, d6, d8, d10, d12, d20, d100 avec animation 3D."},
it:{title:"Lanciare dadi online – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Lancia dadi virtuali online – d4, d6, d8, d10, d12, d20, d100 con animazione 3D."},
pt:{title:"Jogar dados online – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Jogue dados virtuais online – d4, d6, d8, d10, d12, d20, d100 com animação 3D."},
ru:{title:"Бросить кубик онлайн – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Бросайте виртуальные кубики онлайн – d4, d6, d8, d10, d12, d20, d100 с 3D-анимацией."},
cs:{title:"Hodit kostkou online – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Hoďte virtuální kostkou online – d4, d6, d8, d10, d12, d20, d100 s 3D animací."},
uk:{title:"Кинути кубик онлайн – d4, d6, d8, d10, d12, d20, d100 | Losownik.pl",desc:"Кидайте віртуальні кубики онлайн – d4, d6, d8, d10, d12, d20, d100 з 3D-анімацією."}
},

"/mecz":{
en:{title:"Random match score generator – Football, Basketball, Volleyball | Losownik.pl",desc:"Generate a random realistic match score for football, basketball, volleyball or handball."},
de:{title:"Zufälliger Spielergebnis-Generator – Fußball, Basketball, Volleyball | Losownik.pl",desc:"Generiere ein zufälliges realistisches Spielergebnis für Fußball, Basketball, Volleyball oder Handball."},
es:{title:"Generador de resultados aleatorios – Fútbol, Baloncesto, Voleibol | Losownik.pl",desc:"Genera un resultado de partido aleatorio y realista para fútbol, baloncesto, voleibol o balonmano."},
fr:{title:"Générateur de score aléatoire – Football, Basketball, Volley | Losownik.pl",desc:"Générez un score de match aléatoire et réaliste pour football, basketball, volley ou handball."},
it:{title:"Generatore di risultati casuali – Calcio, Basket, Pallavolo | Losownik.pl",desc:"Genera un risultato casuale realistico per calcio, basket, pallavolo o pallamano."},
pt:{title:"Gerador de placar aleatório – Futebol, Basquete, Vôlei | Losownik.pl",desc:"Gere um placar aleatório realista para futebol, basquete, vôlei ou handebol."},
ru:{title:"Генератор случайного счёта – Футбол, Баскетбол, Волейбол | Losownik.pl",desc:"Сгенерируйте случайный реалистичный счёт для футбола, баскетбола, волейбола или гандбола."},
cs:{title:"Generátor náhodného skóre – Fotbal, Basketbal, Volejbal | Losownik.pl",desc:"Vygenerujte náhodné realistické skóre pro fotbal, basketbal, volejbal nebo házenou."},
uk:{title:"Генератор випадкового рахунку – Футбол, Баскетбол, Волейбол | Losownik.pl",desc:"Згенеруйте випадковий реалістичний рахунок для футболу, баскетболу, волейболу або гандболу."}
},

"/imie":{
en:{title:"Random name generator – Male, female names & full identity | Losownik.pl",desc:"Generate a random Polish first name, female name or full identity with statistics."},
de:{title:"Namensgenerator – Männliche, weibliche Namen & volle Identität | Losownik.pl",desc:"Generiere einen zufälligen polnischen Vornamen oder eine vollständige Identität."},
es:{title:"Generador de nombres aleatorios – Masculinos, femeninos e identidad | Losownik.pl",desc:"Genera un nombre polaco aleatorio, masculino, femenino o identidad completa."},
fr:{title:"Générateur de prénoms aléatoires – Masculins, féminins & identité | Losownik.pl",desc:"Générez un prénom polonais aléatoire, masculin, féminin ou une identité complète."},
it:{title:"Generatore di nomi casuali – Maschili, femminili e identità | Losownik.pl",desc:"Genera un nome polacco casuale, maschile, femminile o identità completa."},
pt:{title:"Gerador de nomes aleatórios – Masculinos, femininos e identidade | Losownik.pl",desc:"Gere um nome polonês aleatório, masculino, feminino ou identidade completa."},
ru:{title:"Генератор случайных имён – Мужские, женские и полные данные | Losownik.pl",desc:"Сгенерируйте случайное польское имя, мужское, женское или полную личность."},
cs:{title:"Generátor náhodných jmen – Mužská, ženská a plná identita | Losownik.pl",desc:"Vygenerujte náhodné polské jméno, mužské, ženské nebo plnou identitu."},
uk:{title:"Генератор випадкових імен – Чоловічі, жіночі та повна особа | Losownik.pl",desc:"Згенеруйте випадкове польське ім'я, чоловіче, жіноче або повну особистість."}
},

"/lotto":{
en:{title:"LOTTO number generator – Lucky numbers online | Losownik.pl",desc:"Generate lucky numbers for Lotto, Mini Lotto, Multi Multi and Joker. Free online lottery number generator."},
de:{title:"LOTTO Zahlengenerator – Glückszahlen online | Losownik.pl",desc:"Generiere Glückszahlen für Lotto, Mini Lotto, Multi Multi und Joker. Kostenloser Lotto-Generator."},
es:{title:"Generador de números LOTO – Números de la suerte online | Losownik.pl",desc:"Genera números de la suerte para Loto, Mini Loto, Multi Multi y Joker. Generador gratuito."},
fr:{title:"Générateur LOTO – Numéros chanceux en ligne | Losownik.pl",desc:"Générez des numéros chanceux pour Loto, Mini Loto, Multi Multi et Joker. Gratuit en ligne."},
it:{title:"Generatore numeri LOTTO – Numeri fortunati online | Losownik.pl",desc:"Genera numeri fortunati per Lotto, Mini Lotto, Multi Multi e Joker. Generatore gratuito."},
pt:{title:"Gerador de números LOTO – Números da sorte online | Losownik.pl",desc:"Gere números da sorte para Loto, Mini Loto, Multi Multi e Joker. Gerador gratuito online."},
ru:{title:"Генератор чисел ЛОТО – Счастливые числа онлайн | Losownik.pl",desc:"Сгенерируйте счастливые числа для Лото, Мини Лото, Мульти Мульти и Джокер. Бесплатно."},
cs:{title:"Generátor čísel LOTO – Šťastná čísla online | Losownik.pl",desc:"Vygenerujte šťastná čísla pro Loto, Mini Loto, Multi Multi a Joker. Zdarma online."},
uk:{title:"Генератор чисел ЛОТО – Щасливі числа онлайн | Losownik.pl",desc:"Згенеруйте щасливі числа для Лото, Міні Лото, Мульті Мульті та Джокер. Безкоштовно."}
},

"/wyliczanka":{
en:{title:"Random person picker – Choose one person at random | Losownik.pl",desc:"Enter names and randomly pick one person. Perfect for decisions, raffles and games."},
de:{title:"Zufällige Personenauswahl – Eine Person zufällig wählen | Losownik.pl",desc:"Namen eingeben und eine Person zufällig auswählen. Perfekt für Entscheidungen und Spiele."},
es:{title:"Selector aleatorio de personas – Elige una persona al azar | Losownik.pl",desc:"Introduce nombres y elige una persona al azar. Perfecto para decisiones y juegos."},
fr:{title:"Sélecteur aléatoire – Choisir une personne au hasard | Losownik.pl",desc:"Entrez des noms et choisissez une personne au hasard. Parfait pour les décisions et jeux."},
it:{title:"Selettore casuale di persone – Scegli una persona a caso | Losownik.pl",desc:"Inserisci nomi e scegli una persona a caso. Perfetto per decisioni e giochi."},
pt:{title:"Seletor aleatório de pessoas – Escolha uma pessoa ao acaso | Losownik.pl",desc:"Insira nomes e escolha uma pessoa aleatoriamente. Perfeito para decisões e jogos."},
ru:{title:"Случайный выбор человека – Выберите одного случайно | Losownik.pl",desc:"Введите имена и случайно выберите одного человека. Идеально для решений и игр."},
cs:{title:"Náhodný výběr osoby – Vyberte jednu osobu náhodně | Losownik.pl",desc:"Zadejte jména a náhodně vyberte jednu osobu. Ideální pro rozhodování a hry."},
uk:{title:"Випадковий вибір людини – Оберіть одну людину навмання | Losownik.pl",desc:"Введіть імена та випадково оберіть одну людину. Ідеально для рішень та ігор."}
},

"/liczba":{
en:{title:"Random number generator – Any range | Losownik.pl",desc:"Generate random numbers from any range. Set minimum, maximum and quantity."},
de:{title:"Zufallszahlengenerator – Jeder Bereich | Losownik.pl",desc:"Generiere Zufallszahlen aus jedem Bereich. Minimum, Maximum und Anzahl einstellen."},
es:{title:"Generador de números aleatorios – Cualquier rango | Losownik.pl",desc:"Genera números aleatorios de cualquier rango. Configura mínimo, máximo y cantidad."},
fr:{title:"Générateur de nombres aléatoires – Toute plage | Losownik.pl",desc:"Générez des nombres aléatoires dans n'importe quelle plage. Définissez min, max et quantité."},
it:{title:"Generatore di numeri casuali – Qualsiasi intervallo | Losownik.pl",desc:"Genera numeri casuali da qualsiasi intervallo. Imposta minimo, massimo e quantità."},
pt:{title:"Gerador de números aleatórios – Qualquer faixa | Losownik.pl",desc:"Gere números aleatórios de qualquer faixa. Defina mínimo, máximo e quantidade."},
ru:{title:"Генератор случайных чисел – Любой диапазон | Losownik.pl",desc:"Сгенерируйте случайные числа из любого диапазона. Укажите минимум, максимум и количество."},
cs:{title:"Generátor náhodných čísel – Libovolný rozsah | Losownik.pl",desc:"Vygenerujte náhodná čísla z libovolného rozsahu. Nastavte minimum, maximum a počet."},
uk:{title:"Генератор випадкових чисел – Будь-який діапазон | Losownik.pl",desc:"Згенеруйте випадкові числа з будь-якого діапазону. Вкажіть мінімум, максимум та кількість."}
},

"/kolo-fortuny":{
en:{title:"Spin the Wheel online – Wheel of fortune | Losownik.pl",desc:"Enter options, spin the wheel and let fate decide! Free online wheel of fortune."},
de:{title:"Glücksrad drehen online – Rad der Fortuna | Losownik.pl",desc:"Optionen eingeben, Rad drehen und das Schicksal entscheiden lassen! Kostenloses Glücksrad."},
es:{title:"Girar la ruleta online – Rueda de la fortuna | Losownik.pl",desc:"Introduce opciones, gira la ruleta y deja que el destino decida. Ruleta online gratuita."},
fr:{title:"Tourner la roue en ligne – Roue de la fortune | Losownik.pl",desc:"Entrez des options, tournez la roue et laissez le destin décider ! Roue de fortune gratuite."},
it:{title:"Gira la ruota online – Ruota della fortuna | Losownik.pl",desc:"Inserisci opzioni, gira la ruota e lascia decidere al destino! Ruota della fortuna gratuita."},
pt:{title:"Girar a roda online – Roda da fortuna | Losownik.pl",desc:"Insira opções, gire a roda e deixe o destino decidir! Roda da fortuna gratuita."},
ru:{title:"Колесо фортуны онлайн – Крутите колесо | Losownik.pl",desc:"Введите варианты, крутите колесо и пусть судьба решит! Бесплатное колесо фортуны."},
cs:{title:"Kolo štěstí online – Roztočte kolo | Losownik.pl",desc:"Zadejte možnosti, roztočte kolo a nechte rozhodnout osud! Bezplatné kolo štěstí."},
uk:{title:"Колесо фортуни онлайн – Крутіть колесо | Losownik.pl",desc:"Введіть варіанти, крутіть колесо і нехай доля вирішить! Безкоштовне колесо фортуни."}
},

"/moneta":{
en:{title:"Flip a coin online – Heads or tails | Losownik.pl",desc:"Flip a virtual coin online – heads or tails with realistic animation. Free coin flipper."},
de:{title:"Münze werfen online – Kopf oder Zahl | Losownik.pl",desc:"Wirf eine virtuelle Münze online – Kopf oder Zahl mit realistischer Animation."},
es:{title:"Lanzar moneda online – Cara o cruz | Losownik.pl",desc:"Lanza una moneda virtual online – cara o cruz con animación realista."},
fr:{title:"Pile ou face en ligne – Lancer une pièce | Losownik.pl",desc:"Lancez une pièce virtuelle en ligne – pile ou face avec animation réaliste."},
it:{title:"Lancia moneta online – Testa o croce | Losownik.pl",desc:"Lancia una moneta virtuale online – testa o croce con animazione realistica."},
pt:{title:"Jogar moeda online – Cara ou coroa | Losownik.pl",desc:"Jogue uma moeda virtual online – cara ou coroa com animação realista."},
ru:{title:"Подбросить монету онлайн – Орёл или решка | Losownik.pl",desc:"Подбросьте виртуальную монету онлайн – орёл или решка с реалистичной анимацией."},
cs:{title:"Hodit mincí online – Panna nebo orel | Losownik.pl",desc:"Hoďte virtuální mincí online – panna nebo orel s realistickou animací."},
uk:{title:"Підкинути монету онлайн – Орел чи решка | Losownik.pl",desc:"Підкиньте віртуальну монету онлайн – орел чи решка з реалістичною анімацією."}
},

"/kolor":{
en:{title:"Random color generator – HEX, RGB, HSL | Losownik.pl",desc:"Generate a random color in HEX, RGB or HSL format. Click to copy the color code."},
de:{title:"Zufällige Farbe generieren – HEX, RGB, HSL | Losownik.pl",desc:"Generiere eine zufällige Farbe in HEX, RGB oder HSL. Klicke zum Kopieren."},
es:{title:"Generador de color aleatorio – HEX, RGB, HSL | Losownik.pl",desc:"Genera un color aleatorio en formato HEX, RGB o HSL. Clic para copiar."},
fr:{title:"Générateur de couleur aléatoire – HEX, RGB, HSL | Losownik.pl",desc:"Générez une couleur aléatoire en HEX, RGB ou HSL. Cliquez pour copier."},
it:{title:"Generatore di colore casuale – HEX, RGB, HSL | Losownik.pl",desc:"Genera un colore casuale in formato HEX, RGB o HSL. Clicca per copiare."},
pt:{title:"Gerador de cor aleatória – HEX, RGB, HSL | Losownik.pl",desc:"Gere uma cor aleatória em formato HEX, RGB ou HSL. Clique para copiar."},
ru:{title:"Генератор случайного цвета – HEX, RGB, HSL | Losownik.pl",desc:"Сгенерируйте случайный цвет в формате HEX, RGB или HSL. Нажмите для копирования."},
cs:{title:"Generátor náhodné barvy – HEX, RGB, HSL | Losownik.pl",desc:"Vygenerujte náhodnou barvu ve formátu HEX, RGB nebo HSL. Klikněte pro zkopírování."},
uk:{title:"Генератор випадкового кольору – HEX, RGB, HSL | Losownik.pl",desc:"Згенеруйте випадковий колір у форматі HEX, RGB або HSL. Натисніть для копіювання."}
},

"/karty":{
en:{title:"Draw a random card – Virtual card deck | Losownik.pl",desc:"Draw a random card from a 52-card deck. Cards don't repeat until you shuffle."},
de:{title:"Zufällige Karte ziehen – Virtuelles Kartendeck | Losownik.pl",desc:"Ziehe eine zufällige Karte aus einem 52er-Deck. Karten wiederholen sich nicht bis zum Mischen."},
es:{title:"Sacar carta aleatoria – Baraja virtual | Losownik.pl",desc:"Saca una carta aleatoria de la baraja de 52. Las cartas no se repiten hasta barajar."},
fr:{title:"Tirer une carte aléatoire – Jeu de cartes virtuel | Losownik.pl",desc:"Tirez une carte aléatoire du jeu de 52. Les cartes ne se répètent pas avant le mélange."},
it:{title:"Pescare una carta casuale – Mazzo virtuale | Losownik.pl",desc:"Pesca una carta casuale dal mazzo di 52. Le carte non si ripetono fino al rimescolamento."},
pt:{title:"Tirar carta aleatória – Baralho virtual | Losownik.pl",desc:"Tire uma carta aleatória do baralho de 52. As cartas não se repetem até embaralhar."},
ru:{title:"Вытянуть случайную карту – Виртуальная колода | Losownik.pl",desc:"Вытяните случайную карту из колоды в 52 карты. Карты не повторяются до перетасовки."},
cs:{title:"Vytáhnout náhodnou kartu – Virtuální balíček | Losownik.pl",desc:"Vytáhněte náhodnou kartu z balíčku 52 karet. Karty se neopakují do zamíchání."},
uk:{title:"Витягнути випадкову карту – Віртуальна колода | Losownik.pl",desc:"Витягніть випадкову карту з колоди у 52 карти. Карти не повторюються до перетасування."}
},

"/druzyny":{
en:{title:"Team generator – Divide players into teams | Losownik.pl",desc:"Enter player names and divide them into equal teams randomly. Perfect for sports and games."},
de:{title:"Team-Generator – Spieler in Teams aufteilen | Losownik.pl",desc:"Spielernamen eingeben und zufällig in gleiche Teams aufteilen. Perfekt für Sport und Spiele."},
es:{title:"Generador de equipos – Divide jugadores en equipos | Losownik.pl",desc:"Introduce nombres y divídelos en equipos iguales al azar. Perfecto para deportes y juegos."},
fr:{title:"Générateur d'équipes – Diviser les joueurs en équipes | Losownik.pl",desc:"Entrez les noms et divisez-les en équipes égales aléatoirement. Parfait pour le sport."},
it:{title:"Generatore di squadre – Dividi giocatori in squadre | Losownik.pl",desc:"Inserisci i nomi e dividili in squadre uguali casualmente. Perfetto per sport e giochi."},
pt:{title:"Gerador de equipes – Divida jogadores em equipes | Losownik.pl",desc:"Insira nomes e divida-os em equipes iguais aleatoriamente. Perfeito para esportes e jogos."},
ru:{title:"Генератор команд – Разделите игроков на команды | Losownik.pl",desc:"Введите имена игроков и разделите их на равные команды случайно. Идеально для спорта."},
cs:{title:"Generátor týmů – Rozdělte hráče do týmů | Losownik.pl",desc:"Zadejte jména hráčů a náhodně je rozdělte do stejných týmů. Ideální pro sport a hry."},
uk:{title:"Генератор команд – Поділіть гравців на команди | Losownik.pl",desc:"Введіть імена гравців та поділіть їх на рівні команди випадково. Ідеально для спорту."}
},

"/kolejnosc":{
en:{title:"Random order generator – Shuffle list | Losownik.pl",desc:"Enter items and shuffle them into a random order. Who goes first? Let chance decide!"},
de:{title:"Zufällige Reihenfolge – Liste mischen | Losownik.pl",desc:"Elemente eingeben und in zufälliger Reihenfolge mischen. Wer fängt an?"},
es:{title:"Generador de orden aleatorio – Mezclar lista | Losownik.pl",desc:"Introduce elementos y mézclalos en orden aleatorio. ¿Quién empieza?"},
fr:{title:"Générateur d'ordre aléatoire – Mélanger la liste | Losownik.pl",desc:"Entrez des éléments et mélangez-les dans un ordre aléatoire. Qui commence ?"},
it:{title:"Generatore di ordine casuale – Mescola lista | Losownik.pl",desc:"Inserisci elementi e mescolali in ordine casuale. Chi inizia?"},
pt:{title:"Gerador de ordem aleatória – Embaralhar lista | Losownik.pl",desc:"Insira itens e embaralhe-os em ordem aleatória. Quem começa?"},
ru:{title:"Генератор случайного порядка – Перемешать список | Losownik.pl",desc:"Введите элементы и перемешайте их в случайном порядке. Кто первый?"},
cs:{title:"Generátor náhodného pořadí – Zamíchat seznam | Losownik.pl",desc:"Zadejte položky a zamíchejte je do náhodného pořadí. Kdo začíná?"},
uk:{title:"Генератор випадкового порядку – Перемішати список | Losownik.pl",desc:"Введіть елементи та перемішайте їх у випадковому порядку. Хто перший?"}
},

"/postac":{
en:{title:"RPG character generator – Random stats, race, class | Losownik.pl",desc:"Generate a complete RPG character – random stats, race, class and name. Ready for D&D and tabletop RPGs!"},
de:{title:"RPG-Charakter-Generator – Zufällige Werte, Rasse, Klasse | Losownik.pl",desc:"Generiere einen kompletten RPG-Charakter – Werte, Rasse, Klasse und Name. Für D&D und Tabletop-RPGs!"},
es:{title:"Generador de personajes RPG – Stats, raza, clase aleatorios | Losownik.pl",desc:"Genera un personaje RPG completo – estadísticas, raza, clase y nombre aleatorios. Para D&D!"},
fr:{title:"Générateur de personnage RPG – Stats, race, classe aléatoires | Losownik.pl",desc:"Générez un personnage RPG complet – stats, race, classe et nom aléatoires. Pour D&D !"},
it:{title:"Generatore di personaggi RPG – Statistiche, razza, classe casuali | Losownik.pl",desc:"Genera un personaggio RPG completo – statistiche, razza, classe e nome casuali. Per D&D!"},
pt:{title:"Gerador de personagem RPG – Stats, raça, classe aleatórios | Losownik.pl",desc:"Gere um personagem RPG completo – estatísticas, raça, classe e nome aleatórios. Para D&D!"},
ru:{title:"Генератор персонажей RPG – Случайные характеристики, раса, класс | Losownik.pl",desc:"Сгенерируйте полного персонажа RPG – характеристики, расу, класс и имя. Для D&D!"},
cs:{title:"Generátor postav RPG – Náhodné statistiky, rasa, třída | Losownik.pl",desc:"Vygenerujte kompletní postavu RPG – statistiky, rasu, třídu a jméno. Pro D&D!"},
uk:{title:"Генератор персонажів RPG – Випадкові характеристики, раса, клас | Losownik.pl",desc:"Згенеруйте повного персонажа RPG – характеристики, расу, клас та ім'я. Для D&D!"}
}
};


// PAGE CONTENT TRANSLATIONS
window.LOSOWNIK_T={
"/":{
en:{hero:"Your <span>random generator</span> online",heroDesc:"Roll dice, generate names, predict match scores or test your luck in Lotto. All free, no registration!",cards:{kostka:"Roll dice",kostkaSub:"Dice k4, k6, k8, k12, k20, k100 with 3D animation. Perfect for RPG and board games.",mecz:"Match score",meczSub:"Random score for football, volleyball, basketball or handball.",imie:"Random name",imieSub:"Generate a male, female name or full identity. Popularity statistics.",lotto:"LOTTO",lottoSub:"Generate numbers for Lotto, Mini Lotto, Multi Multi and Joker.",wyliczanka:"Person picker",wyliczankaSub:"Enter names – the tool will randomly pick one person for you.",liczba:"Random number",liczbaSub:"Random number generator from any range. One or many at once.",kolo:"Spin the wheel",koloSub:"Enter options, spin the wheel and let fate decide!",kolor:"Random color",kolorSub:"Generate a color in HEX, RGB or from a palette.",druzyny:"Team generator",druzynySub:"Divide players into equal teams – perfect for team games.",kolejnosc:"Random order",kolejnoscSub:"Shuffle a list and set random order – who goes first?",postac:"RPG Character",postacSub:"Random stats, race, class and name – ready character for tabletop RPGs.",moneta:"Flip a coin",monetaSub:"Heads or tails? Classic coin flip with animation.",karty:"Draw a card",kartySub:"Draw a random card from a 52-card deck. With shuffle sound!"}},

de:{hero:"Dein <span>Zufallsgenerator</span> online",heroDesc:"Würfle, generiere Namen, tippe Spielergebnisse oder teste dein Glück im Lotto. Kostenlos, ohne Registrierung!",cards:{kostka:"Würfeln",kostkaSub:"Würfel k4, k6, k8, k12, k20, k100 mit 3D-Animation.",mecz:"Spielergebnis",meczSub:"Zufälliges Ergebnis für Fußball, Volleyball, Basketball oder Handball.",imie:"Zufälliger Name",imieSub:"Generiere männliche, weibliche Namen oder volle Identität.",lotto:"LOTTO",lottoSub:"Generiere Zahlen für Lotto, Mini Lotto, Multi Multi und Joker.",wyliczanka:"Personenauswahl",wyliczankaSub:"Namen eingeben – das Tool wählt zufällig eine Person.",liczba:"Zufallszahl",liczbaSub:"Zufallszahlengenerator aus jedem Bereich.",kolo:"Glücksrad",koloSub:"Optionen eingeben, Rad drehen und das Schicksal entscheiden lassen!",kolor:"Zufällige Farbe",kolorSub:"Generiere eine Farbe in HEX, RGB oder aus einer Palette.",druzyny:"Team-Generator",druzynySub:"Teile Spieler in gleiche Teams auf.",kolejnosc:"Zufällige Reihenfolge",kolejnoscSub:"Liste mischen – wer fängt an?",postac:"RPG-Charakter",postacSub:"Zufällige Werte, Rasse, Klasse und Name.",moneta:"Münze werfen",monetaSub:"Kopf oder Zahl? Klassischer Münzwurf mit Animation.",karty:"Karte ziehen",kartySub:"Ziehe eine zufällige Karte aus dem 52er-Deck."}},

es:{hero:"Tu <span>generador aleatorio</span> online",heroDesc:"Tira dados, genera nombres, predice resultados o prueba suerte en Loto. ¡Gratis, sin registro!",cards:{kostka:"Tirar dados",kostkaSub:"Dados k4, k6, k8, k12, k20, k100 con animación 3D.",mecz:"Resultado",meczSub:"Resultado aleatorio de fútbol, voleibol, baloncesto o balonmano.",imie:"Nombre aleatorio",imieSub:"Genera nombre masculino, femenino o identidad completa.",lotto:"LOTO",lottoSub:"Genera números para Loto, Mini Loto, Multi Multi y Joker.",wyliczanka:"Selector",wyliczankaSub:"Introduce nombres – la herramienta elegirá uno al azar.",liczba:"Número aleatorio",liczbaSub:"Generador de números de cualquier rango.",kolo:"Ruleta",koloSub:"Introduce opciones, gira la ruleta y ¡deja que decida!",kolor:"Color aleatorio",kolorSub:"Genera un color en HEX, RGB o de una paleta.",druzyny:"Equipos",druzynySub:"Divide jugadores en equipos iguales.",kolejnosc:"Orden aleatorio",kolejnoscSub:"Mezcla la lista – ¿quién empieza?",postac:"Personaje RPG",postacSub:"Estadísticas, raza, clase y nombre aleatorios.",moneta:"Lanzar moneda",monetaSub:"¿Cara o cruz? Lanzamiento clásico con animación.",karty:"Sacar carta",kartySub:"Saca una carta aleatoria de la baraja de 52."}},

fr:{hero:"Votre <span>générateur aléatoire</span> en ligne",heroDesc:"Lancez les dés, générez des prénoms, prédisez des scores ou tentez votre chance au Loto. Gratuit, sans inscription !",cards:{kostka:"Lancer les dés",kostkaSub:"Dés k4, k6, k8, k12, k20, k100 avec animation 3D.",mecz:"Score",meczSub:"Score aléatoire de football, volley, basket ou handball.",imie:"Prénom aléatoire",imieSub:"Générez un prénom masculin, féminin ou une identité complète.",lotto:"LOTO",lottoSub:"Générez des numéros pour Loto, Mini Loto, Multi Multi et Joker.",wyliczanka:"Sélecteur",wyliczankaSub:"Entrez des prénoms – l'outil en choisira un au hasard.",liczba:"Nombre aléatoire",liczbaSub:"Générateur de nombres dans n'importe quelle plage.",kolo:"Roue de la fortune",koloSub:"Entrez des options, tournez la roue et laissez le destin décider !",kolor:"Couleur aléatoire",kolorSub:"Générez une couleur en HEX, RGB ou depuis une palette.",druzyny:"Équipes",druzynySub:"Divisez les joueurs en équipes égales.",kolejnosc:"Ordre aléatoire",kolejnoscSub:"Mélangez la liste – qui commence ?",postac:"Personnage RPG",postacSub:"Stats, race, classe et nom aléatoires.",moneta:"Pile ou face",monetaSub:"Pile ou face ? Lancer classique avec animation.",karty:"Tirer une carte",kartySub:"Tirez une carte aléatoire du jeu de 52."}},

it:{hero:"Il tuo <span>generatore casuale</span> online",heroDesc:"Lancia dadi, genera nomi, prevedi risultati o tenta la fortuna al Lotto. Gratis, senza registrazione!",cards:{kostka:"Lancia dadi",kostkaSub:"Dadi k4, k6, k8, k12, k20, k100 con animazione 3D.",mecz:"Risultato",meczSub:"Risultato casuale di calcio, pallavolo, basket o pallamano.",imie:"Nome casuale",imieSub:"Genera un nome maschile, femminile o identità completa.",lotto:"LOTTO",lottoSub:"Genera numeri per Lotto, Mini Lotto, Multi Multi e Joker.",wyliczanka:"Selettore",wyliczankaSub:"Inserisci nomi – lo strumento ne sceglierà uno a caso.",liczba:"Numero casuale",liczbaSub:"Generatore di numeri da qualsiasi intervallo.",kolo:"Ruota della fortuna",koloSub:"Inserisci opzioni, gira la ruota e lascia decidere al destino!",kolor:"Colore casuale",kolorSub:"Genera un colore in HEX, RGB o da una palette.",druzyny:"Generatore squadre",druzynySub:"Dividi giocatori in squadre uguali.",kolejnosc:"Ordine casuale",kolejnoscSub:"Mescola la lista – chi inizia?",postac:"Personaggio RPG",postacSub:"Statistiche, razza, classe e nome casuali.",moneta:"Lancia moneta",monetaSub:"Testa o croce? Lancio classico con animazione.",karty:"Pesca carta",kartySub:"Pesca una carta casuale dal mazzo di 52."}},

pt:{hero:"Seu <span>gerador aleatório</span> online",heroDesc:"Jogue dados, gere nomes, preveja placares ou tente a sorte na Loto. Grátis, sem registro!",cards:{kostka:"Jogar dados",kostkaSub:"Dados k4, k6, k8, k12, k20, k100 com animação 3D.",mecz:"Placar",meczSub:"Placar aleatório de futebol, vôlei, basquete ou handebol.",imie:"Nome aleatório",imieSub:"Gere um nome masculino, feminino ou identidade completa.",lotto:"LOTO",lottoSub:"Gere números para Loto, Mini Loto, Multi Multi e Joker.",wyliczanka:"Seletor",wyliczankaSub:"Insira nomes – a ferramenta escolherá um ao acaso.",liczba:"Número aleatório",liczbaSub:"Gerador de números de qualquer faixa.",kolo:"Roda da fortuna",koloSub:"Insira opções, gire a roda e deixe o destino decidir!",kolor:"Cor aleatória",kolorSub:"Gere uma cor em HEX, RGB ou de uma paleta.",druzyny:"Gerador de equipes",druzynySub:"Divida jogadores em equipes iguais.",kolejnosc:"Ordem aleatória",kolejnoscSub:"Embaralhe a lista – quem começa?",postac:"Personagem RPG",postacSub:"Estatísticas, raça, classe e nome aleatórios.",moneta:"Jogar moeda",monetaSub:"Cara ou coroa? Lançamento clássico com animação.",karty:"Tirar carta",kartySub:"Tire uma carta aleatória do baralho de 52."}},

ru:{hero:"Ваш <span>генератор случайностей</span> онлайн",heroDesc:"Бросайте кубики, генерируйте имена, предсказывайте счёт или испытайте удачу в Лото. Бесплатно, без регистрации!",cards:{kostka:"Бросить кубик",kostkaSub:"Кубики k4, k6, k8, k12, k20, k100 с 3D-анимацией.",mecz:"Счёт матча",meczSub:"Случайный счёт для футбола, волейбола, баскетбола или гандбола.",imie:"Случайное имя",imieSub:"Сгенерируйте мужское, женское имя или полную личность.",lotto:"ЛОТО",lottoSub:"Сгенерируйте числа для Лото, Мини Лото, Мульти Мульти и Джокер.",wyliczanka:"Выбор человека",wyliczankaSub:"Введите имена – инструмент случайно выберет одного.",liczba:"Случайное число",liczbaSub:"Генератор чисел из любого диапазона.",kolo:"Колесо фортуны",koloSub:"Введите варианты, крутите колесо и пусть судьба решит!",kolor:"Случайный цвет",kolorSub:"Сгенерируйте цвет в HEX, RGB или из палитры.",druzyny:"Генератор команд",druzynySub:"Разделите игроков на равные команды.",kolejnosc:"Случайный порядок",kolejnoscSub:"Перемешайте список – кто первый?",postac:"Персонаж RPG",postacSub:"Случайные характеристики, раса, класс и имя.",moneta:"Подбросить монету",monetaSub:"Орёл или решка? Классический бросок с анимацией.",karty:"Вытянуть карту",kartySub:"Вытяните случайную карту из колоды в 52 карты."}},

cs:{hero:"Váš <span>generátor náhody</span> online",heroDesc:"Hoďte kostkou, generujte jména, tipujte výsledky nebo zkuste štěstí v Lotu. Zdarma, bez registrace!",cards:{kostka:"Hodit kostkou",kostkaSub:"Kostky k4, k6, k8, k12, k20, k100 s 3D animací.",mecz:"Výsledek zápasu",meczSub:"Náhodné skóre pro fotbal, volejbal, basketbal nebo házenou.",imie:"Náhodné jméno",imieSub:"Vygenerujte mužské, ženské jméno nebo plnou identitu.",lotto:"LOTO",lottoSub:"Vygenerujte čísla pro Loto, Mini Loto, Multi Multi a Joker.",wyliczanka:"Výběr osoby",wyliczankaSub:"Zadejte jména – nástroj náhodně vybere jednu osobu.",liczba:"Náhodné číslo",liczbaSub:"Generátor čísel z libovolného rozsahu.",kolo:"Kolo štěstí",koloSub:"Zadejte možnosti, roztočte kolo a nechte rozhodnout osud!",kolor:"Náhodná barva",kolorSub:"Vygenerujte barvu v HEX, RGB nebo z palety.",druzyny:"Generátor týmů",druzynySub:"Rozdělte hráče do stejných týmů.",kolejnosc:"Náhodné pořadí",kolejnoscSub:"Zamíchejte seznam – kdo začíná?",postac:"RPG Postava",postacSub:"Náhodné statistiky, rasa, třída a jméno.",moneta:"Hodit mincí",monetaSub:"Panna nebo orel? Klasický hod s animací.",karty:"Vytáhnout kartu",kartySub:"Vytáhněte náhodnou kartu z balíčku 52 karet."}},

uk:{hero:"Ваш <span>генератор випадковостей</span> онлайн",heroDesc:"Кидайте кубики, генеруйте імена, передбачайте рахунок або випробуйте удачу в Лото. Безкоштовно, без реєстрації!",cards:{kostka:"Кинути кубик",kostkaSub:"Кубики k4, k6, k8, k12, k20, k100 з 3D-анімацією.",mecz:"Рахунок матчу",meczSub:"Випадковий рахунок для футболу, волейболу, баскетболу або гандболу.",imie:"Випадкове ім'я",imieSub:"Згенеруйте чоловіче, жіноче ім'я або повну особистість.",lotto:"ЛОТО",lottoSub:"Згенеруйте числа для Лото, Міні Лото, Мульті Мульті та Джокер.",wyliczanka:"Вибір людини",wyliczankaSub:"Введіть імена – інструмент випадково обере одну людину.",liczba:"Випадкове число",liczbaSub:"Генератор чисел з будь-якого діапазону.",kolo:"Колесо фортуни",koloSub:"Введіть варіанти, крутіть колесо і нехай доля вирішить!",kolor:"Випадковий колір",kolorSub:"Згенеруйте колір у HEX, RGB або з палітри.",druzyny:"Генератор команд",druzynySub:"Поділіть гравців на рівні команди.",kolejnosc:"Випадковий порядок",kolejnoscSub:"Перемішайте список – хто перший?",postac:"Персонаж RPG",postacSub:"Випадкові характеристики, раса, клас та ім'я.",moneta:"Підкинути монету",monetaSub:"Орел чи решка? Класичний кидок з анімацією.",karty:"Витягнути карту",kartySub:"Витягніть випадкову карту з колоди у 52 карти."}}
},

"/kostka":{
en:{h1:"Roll <span>dice</span> online",desc:"Click the dice or button to roll. Choose dice type below.",btn:"Roll dice!",label:"Standard dice (k6)",hint:"Click the dice to roll",opts:"Choose dice type",diceNames:{4:"Tetrahedron (d4)",6:"Cube (d6)",8:"Octahedron (d8)",10:"Decahedron (d10)",12:"Dodecahedron (d12)",20:"Icosahedron (d20)",100:"Percentile (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Is the dice roll truly random?",a:"Yes – we use a cryptographic random number generator (crypto.getRandomValues) which provides true randomness."},{q:"Can I use this for RPG games?",a:"Absolutely! We support all standard RPG dice: d4, d6, d8, d10, d12, d20 and d100."},{q:"Does the 3D animation affect the result?",a:"No – the result is determined instantly by the random generator. The animation is purely visual."}]},

de:{h1:"Online <span>Würfeln</span>",desc:"Klicke auf den Würfel oder Button. Wähle den Würfeltyp unten.",btn:"Würfeln!",label:"Standardwürfel (k6)",hint:"Klicke den Würfel",opts:"Würfeltyp wählen",diceNames:{4:"Tetraeder (W4)",6:"Würfel (W6)",8:"Oktaeder (W8)",10:"Dekaeder (W10)",12:"Dodekaeder (W12)",20:"Ikosaeder (W20)",100:"Prozent (W100)"},diceLabels:{4:"W4",6:"W6",8:"W8",10:"W10",12:"W12",20:"W20",100:"W100"},faq:[{q:"Ist der Würfelwurf wirklich zufällig?",a:"Ja – wir verwenden einen kryptografischen Zufallsgenerator (crypto.getRandomValues)."},{q:"Kann ich das für RPG-Spiele verwenden?",a:"Natürlich! Wir unterstützen alle RPG-Würfel: W4, W6, W8, W10, W12, W20 und W100."},{q:"Beeinflusst die 3D-Animation das Ergebnis?",a:"Nein – das Ergebnis wird sofort vom Zufallsgenerator bestimmt. Die Animation ist rein visuell."}]},

es:{h1:"Tirar <span>dados</span> online",desc:"Haz clic en el dado o botón. Elige el tipo abajo.",btn:"¡Tirar!",label:"Dado estándar (k6)",hint:"Clic en el dado para tirar",opts:"Elige tipo de dado",diceNames:{4:"Tetraedro (d4)",6:"Cubo (d6)",8:"Octaedro (d8)",10:"Decaedro (d10)",12:"Dodecaedro (d12)",20:"Icosaedro (d20)",100:"Percentil (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"¿El dado es realmente aleatorio?",a:"Sí – usamos un generador criptográfico (crypto.getRandomValues) que proporciona verdadera aleatoriedad."},{q:"¿Puedo usarlo para juegos RPG?",a:"¡Por supuesto! Soportamos todos los dados RPG estándar: d4, d6, d8, d10, d12, d20 y d100."},{q:"¿La animación 3D afecta al resultado?",a:"No – el resultado se determina instantáneamente. La animación es puramente visual."}]},

fr:{h1:"Lancer les <span>dés</span> en ligne",desc:"Cliquez sur le dé ou le bouton. Choisissez le type ci-dessous.",btn:"Lancer !",label:"Dé standard (k6)",hint:"Cliquez sur le dé",opts:"Choisir le type",diceNames:{4:"Tétraèdre (d4)",6:"Cube (d6)",8:"Octaèdre (d8)",10:"Décaèdre (d10)",12:"Dodécaèdre (d12)",20:"Icosaèdre (d20)",100:"Percentile (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Le lancer est-il vraiment aléatoire ?",a:"Oui – nous utilisons un générateur cryptographique (crypto.getRandomValues) pour une vraie randomisation."},{q:"Puis-je l'utiliser pour les jeux de rôle ?",a:"Bien sûr ! Nous supportons tous les dés RPG : d4, d6, d8, d10, d12, d20 et d100."},{q:"L'animation 3D affecte-t-elle le résultat ?",a:"Non – le résultat est déterminé instantanément. L'animation est purement visuelle."}]},

it:{h1:"Lancia i <span>dadi</span>",desc:"Clicca il dado o il pulsante per lanciare. Scegli il tipo sotto.",btn:"Lancia!",diceNames:{4:"Tetraedro (d4)",6:"Cubo (d6)",8:"Ottaedro (d8)",10:"Decaedro (d10)",12:"Dodecaedro (d12)",20:"Icosaedro (d20)",100:"Percentile (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Il lancio è veramente casuale?",a:"Sì – utilizziamo un generatore crittografico (crypto.getRandomValues) per una vera casualità."},{q:"Posso usarlo per giochi RPG?",a:"Certamente! Supportiamo tutti i dadi RPG: d4, d6, d8, d10, d12, d20 e d100."},{q:"L'animazione 3D influenza il risultato?",a:"No – il risultato viene determinato istantaneamente. L'animazione è puramente visiva."}]},

pt:{h1:"Jogar <span>dados</span>",desc:"Clique no dado ou botão para jogar. Escolha o tipo abaixo.",btn:"Jogar!",diceNames:{4:"Tetraedro (d4)",6:"Cubo (d6)",8:"Octaedro (d8)",10:"Decaedro (d10)",12:"Dodecaedro (d12)",20:"Icosaedro (d20)",100:"Percentil (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"O lançamento é realmente aleatório?",a:"Sim – usamos um gerador criptográfico (crypto.getRandomValues) para verdadeira aleatoriedade."},{q:"Posso usar para jogos de RPG?",a:"Com certeza! Suportamos todos os dados RPG: d4, d6, d8, d10, d12, d20 e d100."},{q:"A animação 3D afeta o resultado?",a:"Não – o resultado é determinado instantaneamente. A animação é puramente visual."}]},

ru:{h1:"Бросить <span>кубик</span>",desc:"Нажмите на кубик или кнопку. Выберите тип ниже.",btn:"Бросить!",diceNames:{4:"Тетраэдр (d4)",6:"Куб (d6)",8:"Октаэдр (d8)",10:"Декаэдр (d10)",12:"Додекаэдр (d12)",20:"Икосаэдр (d20)",100:"Процентный (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Бросок действительно случайный?",a:"Да – мы используем криптографический генератор (crypto.getRandomValues) для настоящей случайности."},{q:"Можно использовать для RPG?",a:"Конечно! Мы поддерживаем все кубики RPG: d4, d6, d8, d10, d12, d20 и d100."},{q:"Влияет ли 3D-анимация на результат?",a:"Нет – результат определяется мгновенно. Анимация чисто визуальная."}]},

cs:{h1:"Hodit <span>kostkou</span>",desc:"Klikněte na kostku nebo tlačítko. Vyberte typ níže.",btn:"Hodit!",diceNames:{4:"Čtyřstěn (d4)",6:"Kostka (d6)",8:"Osmistěn (d8)",10:"Desetistěn (d10)",12:"Dvanáctistěn (d12)",20:"Dvacetistěn (d20)",100:"Percentil (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Je hod opravdu náhodný?",a:"Ano – používáme kryptografický generátor (crypto.getRandomValues) pro skutečnou náhodnost."},{q:"Mohu to použít pro RPG hry?",a:"Samozřejmě! Podporujeme všechny RPG kostky: d4, d6, d8, d10, d12, d20 a d100."},{q:"Ovlivňuje 3D animace výsledek?",a:"Ne – výsledek je určen okamžitě. Animace je čistě vizuální."}]},

uk:{h1:"Кинути <span>кубик</span>",desc:"Натисніть на кубик або кнопку. Оберіть тип нижче.",btn:"Кинути!",diceNames:{4:"Тетраедр (d4)",6:"Куб (d6)",8:"Октаедр (d8)",10:"Декаедр (d10)",12:"Додекаедр (d12)",20:"Ікосаедр (d20)",100:"Відсотковий (d100)"},diceLabels:{4:"d4",6:"d6",8:"d8",10:"d10",12:"d12",20:"d20",100:"d100"},faq:[{q:"Кидок справді випадковий?",a:"Так – ми використовуємо криптографічний генератор (crypto.getRandomValues) для справжньої випадковості."},{q:"Чи можна використовувати для RPG?",a:"Звичайно! Ми підтримуємо всі кубики RPG: d4, d6, d8, d10, d12, d20 та d100."},{q:"Чи впливає 3D-анімація на результат?",a:"Ні – результат визначається миттєво. Анімація чисто візуальна."}]}
},

"/mecz":{
en:{h1:"Random <span>match</span> score",desc:"Choose a sport and generate a random realistic match score.",btn:"Generate score!",sports:{"Piłka nożna":"Football","Siatkówka":"Volleyball","Piłka ręczna":"Handball","Koszykówka":"Basketball"},faq:[{q:"Are the scores realistic?",a:"Yes – each sport uses its own algorithm that generates scores within typical ranges for that discipline."},{q:"What sports are available?",a:"Football, volleyball, basketball and handball – each with realistic score distributions."},{q:"Can I use this for betting simulations?",a:"This is for entertainment only. The scores are random and have no predictive value."}]},

de:{h1:"Zufälliges <span>Spielergebnis</span>",desc:"Wähle eine Sportart und generiere ein realistisches Ergebnis.",btn:"Generieren!",sports:{"Piłka nożna":"Fußball","Siatkówka":"Volleyball","Piłka ręczna":"Handball","Koszykówka":"Basketball"},faq:[{q:"Sind die Ergebnisse realistisch?",a:"Ja – jede Sportart nutzt einen eigenen Algorithmus mit typischen Ergebnisbereichen."},{q:"Welche Sportarten sind verfügbar?",a:"Fußball, Volleyball, Basketball und Handball – jeweils mit realistischen Ergebnisverteilungen."},{q:"Kann ich das für Wettsimulationen nutzen?",a:"Dies ist nur zur Unterhaltung. Die Ergebnisse sind zufällig und haben keinen Vorhersagewert."}]},

es:{h1:"<span>Resultado</span> aleatorio",desc:"Elige un deporte y genera un resultado realista.",btn:"¡Generar!",sports:{"Piłka nożna":"Fútbol","Siatkówka":"Voleibol","Piłka ręczna":"Balonmano","Koszykówka":"Baloncesto"},faq:[{q:"¿Los resultados son realistas?",a:"Sí – cada deporte usa su propio algoritmo que genera resultados dentro de rangos típicos."},{q:"¿Qué deportes están disponibles?",a:"Fútbol, voleibol, baloncesto y balonmano – cada uno con distribuciones realistas."},{q:"¿Puedo usarlo para simulaciones de apuestas?",a:"Esto es solo entretenimiento. Los resultados son aleatorios y no tienen valor predictivo."}]},

fr:{h1:"<span>Score</span> aléatoire",desc:"Choisissez un sport et générez un score réaliste.",btn:"Générer !",sports:{"Piłka nożna":"Football","Siatkówka":"Volley-ball","Piłka ręczna":"Handball","Koszykówka":"Basketball"},faq:[{q:"Les scores sont-ils réalistes ?",a:"Oui – chaque sport utilise son propre algorithme avec des plages de scores typiques."},{q:"Quels sports sont disponibles ?",a:"Football, volley-ball, basketball et handball – chacun avec des distributions réalistes."},{q:"Puis-je l'utiliser pour des simulations de paris ?",a:"C'est uniquement pour le divertissement. Les scores sont aléatoires et n'ont aucune valeur prédictive."}]},

it:{h1:"<span>Risultato</span> casuale",desc:"Scegli uno sport e genera un risultato realistico.",btn:"Genera!",sports:{"Piłka nożna":"Calcio","Siatkówka":"Pallavolo","Piłka ręczna":"Pallamano","Koszykówka":"Basket"},faq:[{q:"I risultati sono realistici?",a:"Sì – ogni sport usa un algoritmo con intervalli tipici di punteggio."},{q:"Quali sport sono disponibili?",a:"Calcio, pallavolo, basket e pallamano – ognuno con distribuzioni realistiche."},{q:"Posso usarlo per simulazioni di scommesse?",a:"È solo intrattenimento. I risultati sono casuali e non hanno valore predittivo."}]},

pt:{h1:"<span>Resultado</span> aleatório",desc:"Escolha um esporte e gere um placar realista.",btn:"Gerar!",sports:{"Piłka nożna":"Futebol","Siatkówka":"Vôlei","Piłka ręczna":"Handebol","Koszykówka":"Basquete"},faq:[{q:"Os placares são realistas?",a:"Sim – cada esporte usa seu próprio algoritmo com faixas típicas de pontuação."},{q:"Quais esportes estão disponíveis?",a:"Futebol, vôlei, basquete e handebol – cada um com distribuições realistas."},{q:"Posso usar para simulações de apostas?",a:"Isto é apenas entretenimento. Os resultados são aleatórios e não têm valor preditivo."}]},

ru:{h1:"Случайный <span>счёт</span>",desc:"Выберите вид спорта и сгенерируйте реалистичный счёт.",btn:"Генерировать!",sports:{"Piłka nożna":"Футбол","Siatkówka":"Волейбол","Piłka ręczna":"Гандбол","Koszykówka":"Баскетбол"},faq:[{q:"Счёт реалистичный?",a:"Да – каждый вид спорта использует свой алгоритм с типичными диапазонами результатов."},{q:"Какие виды спорта доступны?",a:"Футбол, волейбол, баскетбол и гандбол – каждый с реалистичными распределениями."},{q:"Можно использовать для симуляции ставок?",a:"Это только развлечение. Результаты случайны и не имеют прогнозной ценности."}]},

cs:{h1:"Náhodný <span>výsledek</span>",desc:"Vyberte sport a vygenerujte realistické skóre.",btn:"Generovat!",sports:{"Piłka nożna":"Fotbal","Siatkówka":"Volejbal","Piłka ręczna":"Házená","Koszykówka":"Basketbal"},faq:[{q:"Jsou výsledky realistické?",a:"Ano – každý sport používá vlastní algoritmus s typickými rozsahy skóre."},{q:"Jaké sporty jsou k dispozici?",a:"Fotbal, volejbal, basketbal a házená – každý s realistickým rozdělením."},{q:"Mohu to použít pro simulace sázek?",a:"Toto je pouze zábava. Výsledky jsou náhodné a nemají prediktivní hodnotu."}]},

uk:{h1:"Випадковий <span>рахунок</span>",desc:"Оберіть вид спорту та згенеруйте реалістичний рахунок.",btn:"Генерувати!",sports:{"Piłka nożna":"Футбол","Siatkówka":"Волейбол","Piłka ręczna":"Гандбол","Koszykówka":"Баскетбол"},faq:[{q:"Рахунок реалістичний?",a:"Так – кожен вид спорту використовує свій алгоритм з типовими діапазонами результатів."},{q:"Які види спорту доступні?",a:"Футбол, волейбол, баскетбол та гандбол – кожен з реалістичними розподілами."},{q:"Чи можна використовувати для симуляції ставок?",a:"Це лише розвага. Результати випадкові і не мають прогнозної цінності."}]}
},

"/imie":{
en:{h1:"Random <span>name</span> generator",desc:"Generate a random Polish first name, female name or full identity.",btn:"Generate name!",types:{"Imię męskie":"Male name","Imię żeńskie":"Female name","Imię i nazwisko":"Full name"},faq:[{q:"Where do the names come from?",a:"We use a database of real Polish names with popularity statistics from official records."},{q:"Can I generate a full identity?",a:"Yes – choose 'Full name' to get a first name and surname combination."},{q:"Are the names weighted by popularity?",a:"Yes – more common names appear more frequently, reflecting real Polish naming statistics."}]},

de:{h1:"<span>Namens</span>generator",desc:"Generiere einen zufälligen polnischen Vor- oder Nachnamen.",btn:"Generieren!",types:{"Imię męskie":"Männlich","Imię żeńskie":"Weiblich","Imię i nazwisko":"Vollständig"},faq:[{q:"Woher kommen die Namen?",a:"Wir verwenden eine Datenbank echter polnischer Namen mit Häufigkeitsstatistiken."},{q:"Kann ich eine vollständige Identität generieren?",a:"Ja – wähle 'Vollständig' für eine Kombination aus Vor- und Nachname."},{q:"Sind die Namen nach Häufigkeit gewichtet?",a:"Ja – häufigere Namen erscheinen öfter, basierend auf echten Statistiken."}]},

es:{h1:"Generador de <span>nombres</span>",desc:"Genera un nombre masculino, femenino o identidad completa.",btn:"¡Generar!",types:{"Imię męskie":"Masculino","Imię żeńskie":"Femenino","Imię i nazwisko":"Completo"},faq:[{q:"¿De dónde vienen los nombres?",a:"Usamos una base de datos de nombres polacos reales con estadísticas de popularidad."},{q:"¿Puedo generar una identidad completa?",a:"Sí – elige 'Completo' para obtener nombre y apellido."},{q:"¿Los nombres están ponderados por popularidad?",a:"Sí – los nombres más comunes aparecen con más frecuencia."}]},

fr:{h1:"Générateur de <span>prénoms</span>",desc:"Générez un prénom masculin, féminin ou une identité complète.",btn:"Générer !",types:{"Imię męskie":"Prénom masculin","Imię żeńskie":"Prénom féminin","Imię i nazwisko":"Nom complet"},faq:[{q:"D'où viennent les prénoms ?",a:"Nous utilisons une base de données de prénoms polonais réels avec des statistiques de popularité."},{q:"Puis-je générer une identité complète ?",a:"Oui – choisissez 'Nom complet' pour obtenir prénom et nom de famille."},{q:"Les prénoms sont-ils pondérés par popularité ?",a:"Oui – les prénoms plus courants apparaissent plus fréquemment."}]},

it:{h1:"Generatore di <span>nomi</span>",desc:"Genera un nome maschile, femminile o identità completa.",btn:"Genera!",types:{"Imię męskie":"Maschile","Imię żeńskie":"Femminile","Imię i nazwisko":"Completo"},faq:[{q:"Da dove vengono i nomi?",a:"Utilizziamo un database di nomi polacchi reali con statistiche di popolarità."},{q:"Posso generare un'identità completa?",a:"Sì – scegli 'Completo' per ottenere nome e cognome."},{q:"I nomi sono ponderati per popolarità?",a:"Sì – i nomi più comuni appaiono più frequentemente."}]},

pt:{h1:"Gerador de <span>nomes</span>",desc:"Gere um nome masculino, feminino ou identidade completa.",btn:"Gerar!",types:{"Imię męskie":"Masculino","Imię żeńskie":"Feminino","Imię i nazwisko":"Completo"},faq:[{q:"De onde vêm os nomes?",a:"Usamos um banco de dados de nomes poloneses reais com estatísticas de popularidade."},{q:"Posso gerar uma identidade completa?",a:"Sim – escolha 'Completo' para obter nome e sobrenome."},{q:"Os nomes são ponderados por popularidade?",a:"Sim – nomes mais comuns aparecem com mais frequência."}]},

ru:{h1:"Генератор <span>имён</span>",desc:"Сгенерируйте мужское, женское имя или полную личность.",btn:"Генерировать!",types:{"Imię męskie":"Мужское","Imię żeńskie":"Женское","Imię i nazwisko":"Полное"},faq:[{q:"Откуда берутся имена?",a:"Мы используем базу данных реальных польских имён со статистикой популярности."},{q:"Могу ли я сгенерировать полную личность?",a:"Да – выберите 'Полное' для получения имени и фамилии."},{q:"Имена взвешены по популярности?",a:"Да – более распространённые имена появляются чаще."}]},

cs:{h1:"Generátor <span>jmen</span>",desc:"Vygenerujte mužské, ženské jméno nebo plnou identitu.",btn:"Generovat!",types:{"Imię męskie":"Mužské","Imię żeńskie":"Ženské","Imię i nazwisko":"Celé jméno"},faq:[{q:"Odkud jména pocházejí?",a:"Používáme databázi skutečných polských jmen se statistikami popularity."},{q:"Mohu vygenerovat plnou identitu?",a:"Ano – zvolte 'Celé jméno' pro kombinaci jména a příjmení."},{q:"Jsou jména vážena podle popularity?",a:"Ano – častější jména se objevují častěji."}]},

uk:{h1:"Генератор <span>імен</span>",desc:"Згенеруйте чоловіче, жіноче ім'я або повну особистість.",btn:"Генерувати!",types:{"Imię męskie":"Чоловіче","Imię żeńskie":"Жіноче","Imię i nazwisko":"Повне ім'я"},faq:[{q:"Звідки беруться імена?",a:"Ми використовуємо базу даних реальних польських імен зі статистикою популярності."},{q:"Чи можу я згенерувати повну особистість?",a:"Так – оберіть 'Повне ім'я' для отримання імені та прізвища."},{q:"Імена зважені за популярністю?",a:"Так – більш поширені імена з'являються частіше."}]}
},

"/lotto":{
en:{h1:"<span>LOTTO</span> number generator",desc:"Generate lucky numbers for lottery games. Choose a game and click!",btn:"Generate numbers!",games:{lotto:"Lotto (6 of 49)",minilotto:"Mini Lotto (5 of 42)",multi:"Multi Multi (20 of 80)",joker:"Joker (6 digits)"},faq:[{q:"Are the numbers truly random?",a:"Yes – we use a cryptographic generator for maximum randomness. Each number has an equal chance."},{q:"Can these numbers win the lottery?",a:"The numbers are randomly generated and have the same probability as any other combination."},{q:"What games are supported?",a:"Lotto (6/49), Mini Lotto (5/42), Multi Multi (20/80) and Joker (6/49)."}]},

de:{h1:"<span>LOTTO</span> Zahlengenerator",desc:"Generiere Glückszahlen. Wähle ein Spiel!",btn:"Generieren!",games:{lotto:"Lotto (6 aus 49)",minilotto:"Mini Lotto (5 aus 42)",multi:"Multi Multi (20 aus 80)",joker:"Joker (6 Ziffern)"},faq:[{q:"Sind die Zahlen wirklich zufällig?",a:"Ja – wir nutzen einen kryptografischen Generator für maximale Zufälligkeit."},{q:"Können diese Zahlen im Lotto gewinnen?",a:"Die Zahlen sind zufällig und haben dieselbe Wahrscheinlichkeit wie jede andere Kombination."},{q:"Welche Spiele werden unterstützt?",a:"Lotto (6/49), Mini Lotto (5/42), Multi Multi (20/80) und Joker (6/49)."}]},

es:{h1:"Generador <span>LOTO</span>",desc:"Genera números de la suerte.",btn:"¡Generar!",games:{lotto:"Loto (6 de 49)",minilotto:"Mini Loto (5 de 42)",multi:"Multi Multi (20 de 80)",joker:"Joker (6 dígitos)"},faq:[{q:"¿Los números son realmente aleatorios?",a:"Sí – usamos un generador criptográfico para máxima aleatoriedad."},{q:"¿Pueden estos números ganar la lotería?",a:"Los números son aleatorios y tienen la misma probabilidad que cualquier otra combinación."},{q:"¿Qué juegos se soportan?",a:"Loto (6/49), Mini Loto (5/42), Multi Multi (20/80) y Joker (6/49)."}]},

fr:{h1:"Générateur <span>LOTO</span>",desc:"Générez des numéros chanceux.",btn:"Générer !",games:{lotto:"Loto (6 sur 49)",minilotto:"Mini Loto (5 sur 42)",multi:"Multi Multi (20 sur 80)",joker:"Joker (6 chiffres)"},faq:[{q:"Les numéros sont-ils vraiment aléatoires ?",a:"Oui – nous utilisons un générateur cryptographique pour un maximum de hasard."},{q:"Ces numéros peuvent-ils gagner au loto ?",a:"Les numéros sont aléatoires et ont la même probabilité que toute autre combinaison."},{q:"Quels jeux sont supportés ?",a:"Loto (6/49), Mini Loto (5/42), Multi Multi (20/80) et Joker (6/49)."}]},

it:{h1:"Generatore <span>LOTTO</span>",desc:"Genera numeri fortunati per i giochi della lotteria.",btn:"Genera!",games:{lotto:"Lotto (6 su 49)",minilotto:"Mini Lotto (5 su 42)",multi:"Multi Multi (20 su 80)",joker:"Joker (6 cifre)"},faq:[{q:"I numeri sono veramente casuali?",a:"Sì – utilizziamo un generatore crittografico per la massima casualità."},{q:"Questi numeri possono vincere alla lotteria?",a:"I numeri sono casuali e hanno la stessa probabilità di qualsiasi altra combinazione."},{q:"Quali giochi sono supportati?",a:"Lotto (6/49), Mini Lotto (5/42), Multi Multi (20/80) e Joker (6/49)."}]},

pt:{h1:"Gerador <span>LOTO</span>",desc:"Gere números da sorte para jogos de loteria.",btn:"Gerar!",games:{lotto:"Loto (6 de 49)",minilotto:"Mini Loto (5 de 42)",multi:"Multi Multi (20 de 80)",joker:"Joker (6 dígitos)"},faq:[{q:"Os números são realmente aleatórios?",a:"Sim – usamos um gerador criptográfico para máxima aleatoriedade."},{q:"Esses números podem ganhar na loteria?",a:"Os números são aleatórios e têm a mesma probabilidade que qualquer outra combinação."},{q:"Quais jogos são suportados?",a:"Loto (6/49), Mini Loto (5/42), Multi Multi (20/80) e Joker (6/49)."}]},

ru:{h1:"Генератор <span>ЛОТО</span>",desc:"Сгенерируйте счастливые числа для лотерейных игр.",btn:"Генерировать!",games:{lotto:"Лото (6 из 49)",minilotto:"Мини Лото (5 из 42)",multi:"Мульти Мульти (20 из 80)",joker:"Джокер (6 цифр)"},faq:[{q:"Числа действительно случайные?",a:"Да – мы используем криптографический генератор для максимальной случайности."},{q:"Могут ли эти числа выиграть в лотерею?",a:"Числа случайны и имеют такую же вероятность, как любая другая комбинация."},{q:"Какие игры поддерживаются?",a:"Лото (6/49), Мини Лото (5/42), Мульти Мульти (20/80) и Джокер (6/49)."}]},

cs:{h1:"Generátor <span>LOTO</span>",desc:"Vygenerujte šťastná čísla pro loterijní hry.",btn:"Generovat!",games:{lotto:"Loto (6 z 49)",minilotto:"Mini Loto (5 z 42)",multi:"Multi Multi (20 z 80)",joker:"Joker (6 číslic)"},faq:[{q:"Jsou čísla opravdu náhodná?",a:"Ano – používáme kryptografický generátor pro maximální náhodnost."},{q:"Mohou tato čísla vyhrát v loterii?",a:"Čísla jsou náhodná a mají stejnou pravděpodobnost jako jakákoliv jiná kombinace."},{q:"Jaké hry jsou podporovány?",a:"Loto (6/49), Mini Loto (5/42), Multi Multi (20/80) a Joker (6/49)."}]},

uk:{h1:"Генератор <span>ЛОТО</span>",desc:"Згенеруйте щасливі числа для лотерейних ігор.",btn:"Генерувати!",games:{lotto:"Лото (6 з 49)",minilotto:"Міні Лото (5 з 42)",multi:"Мульті Мульті (20 з 80)",joker:"Джокер (6 з 49)"},faq:[{q:"Числа справді випадкові?",a:"Так – ми використовуємо криптографічний генератор для максимальної випадковості."},{q:"Чи можуть ці числа виграти в лотерею?",a:"Числа випадкові і мають таку ж ймовірність, як будь-яка інша комбінація."},{q:"Які ігри підтримуються?",a:"Лото (6/49), Міні Лото (5/42), Мульті Мульті (20/80) та Джокер (6/49)."}]}
},

"/wyliczanka":{
en:{h1:"<span>Random</span> person picker",desc:"Enter names (one per line) and the tool will randomly pick one person.",btn:"Pick a person!",label:"Enter names (one per line):"},
de:{h1:"<span>Zufällige</span> Personenauswahl",desc:"Namen eingeben (einer pro Zeile).",btn:"Person wählen!",label:"Namen eingeben (einer pro Zeile):"},
es:{h1:"<span>Selector</span> aleatorio",desc:"Introduce nombres (uno por línea).",btn:"¡Elegir!",label:"Introduce nombres (uno por línea):"},
fr:{h1:"<span>Sélecteur</span> aléatoire",desc:"Entrez des prénoms (un par ligne).",btn:"Choisir !",label:"Noms (un par ligne) :"},
it:{h1:"<span>Selettore</span> casuale",desc:"Inserisci nomi (uno per riga).",btn:"Scegli!",label:"Nomi (uno per riga):"},
pt:{h1:"<span>Seletor</span> aleatório",desc:"Insira nomes (um por linha).",btn:"Escolher!",label:"Nomes (um por linha):"},
ru:{h1:"<span>Случайный</span> выбор",desc:"Введите имена (по одному в строке).",btn:"Выбрать!",label:"Введите имена (по одному в строке):"},
cs:{h1:"<span>Náhodný</span> výběr",desc:"Zadejte jména (jedno na řádek).",btn:"Vybrat!",label:"Jména (jedno na řádek):"},
uk:{h1:"<span>Випадковий</span> вибір",desc:"Введіть імена (по одному в рядку).",btn:"Обрати!",label:"Введіть імена (по одному в рядку):"}
},

"/liczba":{
en:{h1:"Random <span>number</span> generator",desc:"Generate random numbers from any range. Set min, max and quantity.",btn:"Generate!"},
de:{h1:"<span>Zufallszahlen</span>generator",desc:"Generiere Zahlen aus jedem Bereich.",btn:"Generieren!"},
es:{h1:"Generador de <span>números</span>",desc:"Genera números de cualquier rango.",btn:"¡Generar!"},
fr:{h1:"Générateur de <span>nombres</span>",desc:"Générez des nombres dans n'importe quelle plage.",btn:"Générer !"},
it:{h1:"Generatore di <span>numeri</span>",desc:"Genera numeri casuali da qualsiasi intervallo.",btn:"Genera!"},
pt:{h1:"Gerador de <span>números</span>",desc:"Gere números aleatórios de qualquer faixa.",btn:"Gerar!"},
ru:{h1:"Генератор <span>чисел</span>",desc:"Сгенерируйте случайные числа из любого диапазона.",btn:"Генерировать!"},
cs:{h1:"Generátor <span>čísel</span>",desc:"Vygenerujte náhodná čísla z libovolného rozsahu.",btn:"Generovat!"},
uk:{h1:"Генератор <span>чисел</span>",desc:"Згенеруйте випадкові числа з будь-якого діапазону.",btn:"Генерувати!"}
},

"/kolo-fortuny":{
en:{h1:"<span>Spin the Wheel</span> online",desc:"Enter options (one per line), spin the wheel and let fate decide!",btn:"Spin!",label:"Options (one per line):"},
de:{h1:"<span>Glücksrad</span> online",desc:"Optionen eingeben, Rad drehen!",btn:"Drehen!",label:"Optionen (eine pro Zeile):"},
es:{h1:"<span>Ruleta</span> online",desc:"Introduce opciones, gira la ruleta.",btn:"¡Girar!",label:"Opciones (una por línea):"},
fr:{h1:"<span>Roue de la fortune</span>",desc:"Entrez des options, tournez la roue !",btn:"Tourner !",label:"Options (une par ligne) :"},
it:{h1:"<span>Ruota della fortuna</span>",desc:"Inserisci opzioni, gira la ruota e lascia decidere al destino!",btn:"Gira!",label:"Opzioni (una per riga):"},
pt:{h1:"<span>Roda da fortuna</span>",desc:"Insira opções, gire a roda e deixe o destino decidir!",btn:"Girar!",label:"Opções (uma por linha):"},
ru:{h1:"<span>Колесо фортуны</span>",desc:"Введите варианты, крутите колесо и пусть судьба решит!",btn:"Крутить!",label:"Варианты (по одному в строке):"},
cs:{h1:"<span>Kolo štěstí</span>",desc:"Zadejte možnosti, roztočte kolo a nechte rozhodnout osud!",btn:"Točit!",label:"Možnosti (jedna na řádek):"},
uk:{h1:"<span>Колесо фортуни</span>",desc:"Введіть варіанти, крутіть колесо і нехай доля вирішить!",btn:"Крутити!",label:"Варіанти (по одному в рядку):"}
},

"/moneta":{
en:{h1:"<span>Flip a coin</span> online",desc:"Heads or tails? Click the coin or button to flip!",btn:"Flip coin!",faq:[{q:"Is the coin flip fair?",a:"Yes – each side has an exact 50% probability using a cryptographic random generator."},{q:"Can I see the flip history?",a:"Yes – all flips are recorded in the history section with timestamps."},{q:"Does the animation affect the result?",a:"No – the result is determined instantly. The animation is purely visual."}]},
de:{h1:"<span>Münze werfen</span>",desc:"Kopf oder Zahl? Klicke die Münze!",btn:"Werfen!",faq:[{q:"Ist der Münzwurf fair?",a:"Ja – jede Seite hat exakt 50% Wahrscheinlichkeit."},{q:"Kann ich den Verlauf sehen?",a:"Ja – alle Würfe werden mit Zeitstempel aufgezeichnet."},{q:"Beeinflusst die Animation das Ergebnis?",a:"Nein – das Ergebnis wird sofort bestimmt. Die Animation ist rein visuell."}]},
es:{h1:"<span>Lanzar moneda</span>",desc:"¿Cara o cruz? Haz clic.",btn:"¡Lanzar!",faq:[{q:"¿El lanzamiento es justo?",a:"Sí – cada lado tiene exactamente 50% de probabilidad."},{q:"¿Puedo ver el historial?",a:"Sí – todos los lanzamientos se registran con marca de tiempo."},{q:"¿La animación afecta al resultado?",a:"No – el resultado se determina instantáneamente. La animación es puramente visual."}]},
fr:{h1:"<span>Pile ou face</span>",desc:"Pile ou face ? Cliquez !",btn:"Lancer !",faq:[{q:"Le lancer est-il équitable ?",a:"Oui – chaque face a exactement 50% de probabilité."},{q:"Puis-je voir l'historique ?",a:"Oui – tous les lancers sont enregistrés avec horodatage."},{q:"L'animation affecte-t-elle le résultat ?",a:"Non – le résultat est déterminé instantanément. L'animation est purement visuelle."}]},

it:{h1:"<span>Lancia moneta</span>",desc:"Testa o croce? Clicca la moneta o il pulsante!",btn:"Lancia!",faq:[{q:"Il lancio è equo?",a:"Sì – ogni lato ha esattamente il 50% di probabilità."},{q:"Posso vedere la cronologia?",a:"Sì – tutti i lanci sono registrati con timestamp."},{q:"L'animazione influenza il risultato?",a:"No – il risultato viene determinato istantaneamente."}]},
pt:{h1:"<span>Jogar moeda</span>",desc:"Cara ou coroa? Clique na moeda ou botão!",btn:"Jogar!",faq:[{q:"O lançamento é justo?",a:"Sim – cada lado tem exatamente 50% de probabilidade."},{q:"Posso ver o histórico?",a:"Sim – todos os lançamentos são registrados com timestamp."},{q:"A animação afeta o resultado?",a:"Não – o resultado é determinado instantaneamente."}]},
ru:{h1:"<span>Подбросить монету</span>",desc:"Орёл или решка? Нажмите на монету или кнопку!",btn:"Подбросить!",faq:[{q:"Подбрасывание честное?",a:"Да – каждая сторона имеет ровно 50% вероятности."},{q:"Могу ли я увидеть историю?",a:"Да – все подбрасывания записываются с временными метками."},{q:"Влияет ли анимация на результат?",a:"Нет – результат определяется мгновенно. Анимация чисто визуальная."}]},
cs:{h1:"<span>Hodit mincí</span>",desc:"Panna nebo orel? Klikněte na minci nebo tlačítko!",btn:"Hodit!",faq:[{q:"Je hod spravedlivý?",a:"Ano – každá strana má přesně 50% pravděpodobnost."},{q:"Mohu vidět historii?",a:"Ano – všechny hody jsou zaznamenány s časovým razítkem."},{q:"Ovlivňuje animace výsledek?",a:"Ne – výsledek je určen okamžitě. Animace je čistě vizuální."}]},
uk:{h1:"<span>Підкинути монету</span>",desc:"Орел чи решка? Натисніть на монету або кнопку!",btn:"Підкинути!",faq:[{q:"Підкидання чесне?",a:"Так – кожна сторона має рівно 50% ймовірності."},{q:"Чи можу я побачити історію?",a:"Так – усі підкидання записуються з часовими мітками."},{q:"Чи впливає анімація на результат?",a:"Ні – результат визначається миттєво. Анімація чисто візуальна."}]}
},

"/kolor":{
en:{h1:"Random <span>color</span>",desc:"Generate a random color. Click a code to copy to clipboard.",btn:"Generate color!"},
de:{h1:"Zufällige <span>Farbe</span>",desc:"Generiere eine Farbe. Klicke zum Kopieren.",btn:"Generieren!"},
es:{h1:"<span>Color</span> aleatorio",desc:"Genera un color. Clic para copiar.",btn:"¡Generar!"},
fr:{h1:"<span>Couleur</span> aléatoire",desc:"Générez une couleur. Cliquez pour copier.",btn:"Générer !"},
it:{h1:"<span>Colore</span> casuale",desc:"Genera un colore casuale. Clicca un codice per copiare.",btn:"Genera!"},
pt:{h1:"<span>Cor</span> aleatória",desc:"Gere uma cor aleatória. Clique no código para copiar.",btn:"Gerar!"},
ru:{h1:"Случайный <span>цвет</span>",desc:"Сгенерируйте случайный цвет. Нажмите на код для копирования.",btn:"Генерировать!"},
cs:{h1:"Náhodná <span>barva</span>",desc:"Vygenerujte náhodnou barvu. Klikněte na kód pro zkopírování.",btn:"Generovat!"},
uk:{h1:"Випадковий <span>колір</span>",desc:"Згенеруйте випадковий колір. Натисніть на код для копіювання.",btn:"Генерувати!"}
},

"/karty":{
en:{h1:"<span>Draw</span> a card",desc:"Draw a random card from a 52-card deck. Cards don't repeat until shuffle.",btn:"Draw card!",hint:"Cards remaining in the deck"},
de:{h1:"<span>Karte</span> ziehen",desc:"Ziehe eine Karte aus dem 52er-Deck.",btn:"Ziehen!",hint:"Verbleibende Karten im Deck"},
es:{h1:"<span>Sacar</span> carta",desc:"Saca una carta de la baraja de 52.",btn:"¡Sacar!",hint:"Cartas restantes en la baraja"},
fr:{h1:"<span>Tirer</span> une carte",desc:"Tirez une carte du jeu de 52.",btn:"Tirer !",hint:"Cartes restantes dans le jeu"},
it:{h1:"<span>Pesca</span> carta",desc:"Pesca una carta casuale dal mazzo di 52. Le carte non si ripetono.",btn:"Pesca!",hint:"Carte rimanenti nel mazzo"},
pt:{h1:"<span>Tirar</span> carta",desc:"Tire uma carta aleatória do baralho de 52.",btn:"Tirar!",hint:"Cartas restantes no baralho"},
ru:{h1:"<span>Вытянуть</span> карту",desc:"Вытяните случайную карту из колоды в 52 карты.",btn:"Вытянуть!",hint:"Карт осталось в колоде"},
cs:{h1:"<span>Vytáhnout</span> kartu",desc:"Vytáhněte náhodnou kartu z balíčku 52 karet.",btn:"Vytáhnout!",hint:"Zbývající karty v balíčku"},
uk:{h1:"<span>Витягнути</span> карту",desc:"Витягніть випадкову карту з колоди у 52 карти.",btn:"Витягнути!",hint:"Карт залишилось у колоді"}
},

"/druzyny":{
en:{h1:"<span>Team</span> generator",desc:"Enter player names and choose number of teams.",btn:"Divide!"},
de:{h1:"<span>Team</span>-Generator",desc:"Spielernamen eingeben und Teams wählen.",btn:"Aufteilen!"},
es:{h1:"Generador de <span>equipos</span>",desc:"Introduce nombres y elige número de equipos.",btn:"¡Dividir!"},
fr:{h1:"Générateur d'<span>équipes</span>",desc:"Entrez les noms et le nombre d'équipes.",btn:"Diviser !"},
it:{h1:"Generatore <span>squadre</span>",desc:"Inserisci i nomi dei giocatori e scegli il numero di squadre.",btn:"Dividi!"},
pt:{h1:"Gerador de <span>equipes</span>",desc:"Insira nomes dos jogadores e escolha o número de equipes.",btn:"Dividir!"},
ru:{h1:"Генератор <span>команд</span>",desc:"Введите имена игроков и выберите количество команд.",btn:"Разделить!"},
cs:{h1:"Generátor <span>týmů</span>",desc:"Zadejte jména hráčů a zvolte počet týmů.",btn:"Rozdělit!"},
uk:{h1:"Генератор <span>команд</span>",desc:"Введіть імена гравців та оберіть кількість команд.",btn:"Поділити!"}
},

"/kolejnosc":{
en:{h1:"Random <span>order</span>",desc:"Enter items and shuffle randomly. Who goes first?",btn:"Shuffle!"},
de:{h1:"Zufällige <span>Reihenfolge</span>",desc:"Elemente eingeben und mischen.",btn:"Mischen!"},
es:{h1:"<span>Orden</span> aleatorio",desc:"Introduce elementos y mézclalos.",btn:"¡Mezclar!"},
fr:{h1:"<span>Ordre</span> aléatoire",desc:"Entrez des éléments et mélangez.",btn:"Mélanger !"},
it:{h1:"<span>Ordine</span> casuale",desc:"Inserisci elementi e mescolali casualmente.",btn:"Mescola!"},
pt:{h1:"<span>Ordem</span> aleatória",desc:"Insira itens e embaralhe aleatoriamente.",btn:"Embaralhar!"},
ru:{h1:"Случайный <span>порядок</span>",desc:"Введите элементы и перемешайте случайно.",btn:"Перемешать!"},
cs:{h1:"Náhodné <span>pořadí</span>",desc:"Zadejte položky a zamíchejte náhodně.",btn:"Zamíchat!"},
uk:{h1:"Випадковий <span>порядок</span>",desc:"Введіть елементи та перемішайте випадково.",btn:"Перемішати!"}
},

"/postac":{
en:{h1:"<span>RPG</span> Character Generator",desc:"Generate a complete character – stats, race, class and name. Ready for D&D!",btn:"Generate!"},
de:{h1:"<span>RPG</span>-Charakter-Generator",desc:"Generiere einen kompletten Charakter.",btn:"Generieren!"},
es:{h1:"Generador de personajes <span>RPG</span>",desc:"Genera un personaje completo.",btn:"¡Generar!"},
fr:{h1:"Générateur <span>RPG</span>",desc:"Générez un personnage complet.",btn:"Générer !"},
it:{h1:"Generatore <span>RPG</span>",desc:"Genera un personaggio completo – statistiche, razza, classe e nome.",btn:"Genera!"},
pt:{h1:"Gerador <span>RPG</span>",desc:"Gere um personagem completo – estatísticas, raça, classe e nome.",btn:"Gerar!"},
ru:{h1:"Генератор персонажей <span>RPG</span>",desc:"Сгенерируйте полного персонажа – характеристики, расу, класс и имя.",btn:"Генерировать!"},
cs:{h1:"Generátor postav <span>RPG</span>",desc:"Vygenerujte kompletní postavu – statistiky, rasu, třídu a jméno.",btn:"Generovat!"},
uk:{h1:"Генератор персонажів <span>RPG</span>",desc:"Згенеруйте повного персонажа – характеристики, расу, клас та ім'я.",btn:"Генерувати!"}
}
};
